PREFIX : <http://ksg.meraka.co.za/adolena.owl#>
PREFIX NAP: <file:///home/aurona/0AlleWerk/Navorsing/Ontologies/NAP/NAP#>

SELECT ?0 WHERE {
?0 a NAP:Device.
?0 :assistsWith ?1.
?1 a NAP:UpperLimbMobility.
}