CREATE TABLE "src_AdministrativeStaff" (c0 text);
CREATE TABLE "src_Article" (c0 text);
CREATE TABLE "src_AssistantProfessor" (c0 text);
CREATE TABLE "src_AssociateProfessor" (c0 text);
CREATE TABLE "src_Book" (c0 text);
CREATE TABLE "src_Chair" (c0 text);
CREATE TABLE "src_ClericalStaff" (c0 text);
CREATE TABLE "src_College" (c0 text);
CREATE TABLE "src_ConferencePaper" (c0 text);
CREATE TABLE "src_Course" (c0 text);
CREATE TABLE "src_Dean" (c0 text);
CREATE TABLE "src_Department" (c0 text);
CREATE TABLE "src_Director" (c0 text);
CREATE TABLE "src_Employee" (c0 text);
CREATE TABLE "src_Faculty" (c0 text);
CREATE TABLE "src_FullProfessor" (c0 text);
CREATE TABLE "src_GraduateCourse" (c0 text);
CREATE TABLE "src_GraduateStudent" (c0 text);
CREATE TABLE "src_Institute" (c0 text);
CREATE TABLE "src_JournalArticle" (c0 text);
CREATE TABLE "src_Lecturer" (c0 text);
CREATE TABLE "src_Manual" (c0 text);
CREATE TABLE "src_Organization" (c0 text);
CREATE TABLE "src_Person" (c0 text);
CREATE TABLE "src_PostDoc" (c0 text);
CREATE TABLE "src_Professor" (c0 text);
CREATE TABLE "src_Program" (c0 text);
CREATE TABLE "src_Publication" (c0 text);
CREATE TABLE "src_Research" (c0 text);
CREATE TABLE "src_ResearchAssistant" (c0 text);
CREATE TABLE "src_ResearchGroup" (c0 text);
CREATE TABLE "src_Schedule" (c0 text);
CREATE TABLE "src_Software" (c0 text);
CREATE TABLE "src_Specification" (c0 text);
CREATE TABLE "src_Student" (c0 text);
CREATE TABLE "src_SystemsStaff" (c0 text);
CREATE TABLE "src_TeachingAssistant" (c0 text);
CREATE TABLE "src_TechnicalReport" (c0 text);
CREATE TABLE "src_UndergraduateStudent" (c0 text);
CREATE TABLE "src_University" (c0 text);
CREATE TABLE "src_UnofficialPublication" (c0 text);
CREATE TABLE "src_VisitingProfessor" (c0 text);
CREATE TABLE "src_Work" (c0 text);
CREATE TABLE "src_age" (c0 text, c1 integer);
CREATE TABLE "src_advisor" (c0 text, c1 text);
CREATE TABLE "src_affiliateOf" (c0 text, c1 text);
CREATE TABLE "src_affiliatedOrganizationOf" (c0 text, c1 text);
CREATE TABLE "src_degreeFrom" (c0 text, c1 text);
CREATE TABLE "src_doctoralDegreeFrom" (c0 text, c1 text);
CREATE TABLE "src_emailAddress" (c0 text, c1 text);
CREATE TABLE "src_hasAlumnus" (c0 text, c1 text);
CREATE TABLE "src_headOf" (c0 text, c1 text);
CREATE TABLE "src_listedCourse" (c0 text, c1 text);
CREATE TABLE "src_mastersDegreeFrom" (c0 text, c1 text);
CREATE TABLE "src_member" (c0 text, c1 text);
CREATE TABLE "src_memberOf" (c0 text, c1 text);
CREATE TABLE "src_name" (c0 text, c1 text);
CREATE TABLE "src_orgPublication" (c0 text, c1 text);
CREATE TABLE "src_publicationAuthor" (c0 text, c1 text);
CREATE TABLE "src_publicationDate" (c0 text, c1 text);
CREATE TABLE "src_publicationResearch" (c0 text, c1 text);
CREATE TABLE "src_researchInterest" (c0 text, c1 text);
CREATE TABLE "src_researchProject" (c0 text, c1 text);
CREATE TABLE "src_softwareDocumentation" (c0 text, c1 text);
CREATE TABLE "src_softwareVersion" (c0 text, c1 integer);
CREATE TABLE "src_subOrganizationOf" (c0 text, c1 text);
CREATE TABLE "src_takesCourse" (c0 text, c1 text);
CREATE TABLE "src_teacherOf" (c0 text, c1 text);
CREATE TABLE "src_teachingAssistantOf" (c0 text, c1 text);
CREATE TABLE "src_telephone" (c0 text, c1 text);
CREATE TABLE "src_tenured" (c0 text, c1 integer);
CREATE TABLE "src_title" (c0 text, c1 text);
CREATE TABLE "src_undergraduateDegreeFrom" (c0 text, c1 text);
CREATE TABLE "src_worksFor" (c0 text, c1 text);