DROP TABLE IF EXISTS "src_Dramaturge";
CREATE TABLE "src_Dramaturge" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Religious-Leader";
CREATE TABLE "src_Religious-Leader" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Field-of-Knowledge";
CREATE TABLE "src_Field-of-Knowledge" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Village";
CREATE TABLE "src_Village" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Party";
CREATE TABLE "src_Party" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Philosopher";
CREATE TABLE "src_Philosopher" (c0 text);
DROP TABLE IF EXISTS "src_Film-Maker";
CREATE TABLE "src_Film-Maker" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Publisher";
CREATE TABLE "src_Publisher" (c0 text);
DROP TABLE IF EXISTS "src_Trial";
CREATE TABLE "src_Trial" (c0 text);
DROP TABLE IF EXISTS "src_Philanthropist";
CREATE TABLE "src_Philanthropist" (c0 text);
DROP TABLE IF EXISTS "src_Newspaper";
CREATE TABLE "src_Newspaper" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Pollution";
CREATE TABLE "src_Pollution" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Environment";
CREATE TABLE "src_Environment" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Military-Person";
CREATE TABLE "src_Military-Person" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Management-Organisation";
CREATE TABLE "src_Management-Organisation" (c0 text);
DROP TABLE IF EXISTS "src_Cleric";
CREATE TABLE "src_Cleric" (c0 text);
DROP TABLE IF EXISTS "src_Criminal";
CREATE TABLE "src_Criminal" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Queen";
CREATE TABLE "src_Queen" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Masonic-Lodge";
CREATE TABLE "src_Masonic-Lodge" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Theologian";
CREATE TABLE "src_Theologian" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Settlement";
CREATE TABLE "src_Settlement" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Artist";
CREATE TABLE "src_Artist" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Emperor";
CREATE TABLE "src_Emperor" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Pamphlet";
CREATE TABLE "src_Pamphlet" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Geographical-Feature";
CREATE TABLE "src_Geographical-Feature" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Secular-Ideology";
CREATE TABLE "src_Secular-Ideology" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Engineer";
CREATE TABLE "src_Engineer" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Period-in-Office";
CREATE TABLE "src_Period-in-Office" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Location";
CREATE TABLE "src_Location" (c0 text);
DROP TABLE IF EXISTS "src_Artistic-Movement";
CREATE TABLE "src_Artistic-Movement" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Saint";
CREATE TABLE "src_Saint" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Creator";
CREATE TABLE "src_Creator" (c0 text);
DROP TABLE IF EXISTS "src_University";
CREATE TABLE "src_University" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Actor";
CREATE TABLE "src_Actor" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Category";
CREATE TABLE "src_Category" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Time-Dependent-Relation";
CREATE TABLE "src_Time-Dependent-Relation" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Business-Leader";
CREATE TABLE "src_Business-Leader" (c0 text);
DROP TABLE IF EXISTS "src_hasRelationMember";
CREATE TABLE "src_hasRelationMember" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Writing";
CREATE TABLE "src_Writing" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Piece-of-Music";
CREATE TABLE "src_Piece-of-Music" (c0 text);
DROP TABLE IF EXISTS "src_Economist";
CREATE TABLE "src_Economist" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_isLocationContainerMemberOf";
CREATE TABLE "src_isLocationContainerMemberOf" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Abstract-Notion";
CREATE TABLE "src_Abstract-Notion" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Intellectual-Construct";
CREATE TABLE "src_Intellectual-Construct" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Idea";
CREATE TABLE "src_Idea" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Military-Unit";
CREATE TABLE "src_Military-Unit" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Ideology";
CREATE TABLE "src_Ideology" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Intellectual-Movement";
CREATE TABLE "src_Intellectual-Movement" (c0 text);
DROP TABLE IF EXISTS "src_Foreign-Minister";
CREATE TABLE "src_Foreign-Minister" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Individual";
CREATE TABLE "src_Individual" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_FuzzyTemporalInterval";
CREATE TABLE "src_FuzzyTemporalInterval" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Sculpture";
CREATE TABLE "src_Sculpture" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Event";
CREATE TABLE "src_Event" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Book";
CREATE TABLE "src_Book" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Religious-Community";
CREATE TABLE "src_Religious-Community" (c0 text);
DROP TABLE IF EXISTS "src_War";
CREATE TABLE "src_War" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Non-Military-Conflict";
CREATE TABLE "src_Non-Military-Conflict" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_TemporalInterval";
CREATE TABLE "src_TemporalInterval" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Disaster";
CREATE TABLE "src_Disaster" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Psychologist";
CREATE TABLE "src_Psychologist" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Illness";
CREATE TABLE "src_Illness" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Minister";
CREATE TABLE "src_Minister" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Pastime";
CREATE TABLE "src_Pastime" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Badge";
CREATE TABLE "src_Badge" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Secular-Leader";
CREATE TABLE "src_Secular-Leader" (c0 text);
DROP TABLE IF EXISTS "src_Representative-Institution";
CREATE TABLE "src_Representative-Institution" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Jurist";
CREATE TABLE "src_Jurist" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Location-Part-Relation";
CREATE TABLE "src_Location-Part-Relation" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Time";
CREATE TABLE "src_Time" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Ecclesiarch";
CREATE TABLE "src_Ecclesiarch" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Other-Religious-Leader";
CREATE TABLE "src_Other-Religious-Leader" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Diplomat";
CREATE TABLE "src_Diplomat" (c0 text);
DROP TABLE IF EXISTS "src_Politician";
CREATE TABLE "src_Politician" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Magnate";
CREATE TABLE "src_Magnate" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Entertainer";
CREATE TABLE "src_Entertainer" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Scientist";
CREATE TABLE "src_Scientist" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Head-of-State";
CREATE TABLE "src_Head-of-State" (c0 text);
DROP TABLE IF EXISTS "src_Economic-Organisation";
CREATE TABLE "src_Economic-Organisation" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Journal";
CREATE TABLE "src_Journal" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Stereotype-Group";
CREATE TABLE "src_Stereotype-Group" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Social-Group";
CREATE TABLE "src_Social-Group" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Treaty";
CREATE TABLE "src_Treaty" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Sultan";
CREATE TABLE "src_Sultan" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_National-Symbol";
CREATE TABLE "src_National-Symbol" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Crime";
CREATE TABLE "src_Crime" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Economic-Enterprise";
CREATE TABLE "src_Economic-Enterprise" (c0 text);
DROP TABLE IF EXISTS "src_hasLocationContainerMember";
CREATE TABLE "src_hasLocationContainerMember" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Battle";
CREATE TABLE "src_Battle" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Musician";
CREATE TABLE "src_Musician" (c0 text);
DROP TABLE IF EXISTS "src_Landmark";
CREATE TABLE "src_Landmark" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Functionary";
CREATE TABLE "src_Functionary" (c0 text);
DROP TABLE IF EXISTS "src_Uprising";
CREATE TABLE "src_Uprising" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Organisation";
CREATE TABLE "src_Organisation" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Governmental-Organisation";
CREATE TABLE "src_Governmental-Organisation" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Trades-Union";
CREATE TABLE "src_Trades-Union" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Political-Organisation";
CREATE TABLE "src_Political-Organisation" (c0 text);
DROP TABLE IF EXISTS "src_Armament";
CREATE TABLE "src_Armament" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_hasRole";
CREATE TABLE "src_hasRole" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Movement";
CREATE TABLE "src_Movement" (c0 text);
DROP TABLE IF EXISTS "src_Trade-Association";
CREATE TABLE "src_Trade-Association" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Country";
CREATE TABLE "src_Country" (c0 text);
DROP TABLE IF EXISTS "src_Clothing";
CREATE TABLE "src_Clothing" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Dynasty";
CREATE TABLE "src_Dynasty" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Natural-Object";
CREATE TABLE "src_Natural-Object" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Author";
CREATE TABLE "src_Author" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Conceptual-Object";
CREATE TABLE "src_Conceptual-Object" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Religious-Practice";
CREATE TABLE "src_Religious-Practice" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Role";
CREATE TABLE "src_Role" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Animal";
CREATE TABLE "src_Animal" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Architect";
CREATE TABLE "src_Architect" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Commodity";
CREATE TABLE "src_Commodity" (c0 text);
DROP TABLE IF EXISTS "src_Cultural-Agreement";
CREATE TABLE "src_Cultural-Agreement" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Economic-Symbol";
CREATE TABLE "src_Economic-Symbol" (c0 text);
DROP TABLE IF EXISTS "src_hasLocationPartMember";
CREATE TABLE "src_hasLocationPartMember" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Food";
CREATE TABLE "src_Food" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Structure";
CREATE TABLE "src_Structure" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Life-Event";
CREATE TABLE "src_Life-Event" (c0 text);
DROP TABLE IF EXISTS "src_Religious-Movement";
CREATE TABLE "src_Religious-Movement" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Clerical-Leader";
CREATE TABLE "src_Clerical-Leader" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Political-Symbol";
CREATE TABLE "src_Political-Symbol" (c0 text);
DROP TABLE IF EXISTS "src_Conductor";
CREATE TABLE "src_Conductor" (c0 text);
DROP TABLE IF EXISTS "src_Symbol";
CREATE TABLE "src_Symbol" (c0 text);
DROP TABLE IF EXISTS "src_Technical-Scientific-Advance";
CREATE TABLE "src_Technical-Scientific-Advance" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Religious-Organisation";
CREATE TABLE "src_Religious-Organisation" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Church-Reformer";
CREATE TABLE "src_Church-Reformer" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Meeting";
CREATE TABLE "src_Meeting" (c0 text);
DROP TABLE IF EXISTS "src_Scientific-Instrument";
CREATE TABLE "src_Scientific-Instrument" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_International-Alliance";
CREATE TABLE "src_International-Alliance" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Ritual";
CREATE TABLE "src_Ritual" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Time-Dependent";
CREATE TABLE "src_Time-Dependent" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Religious-Order";
CREATE TABLE "src_Religious-Order" (c0 text);
DROP TABLE IF EXISTS "src_Sculptor";
CREATE TABLE "src_Sculptor" (c0 text);
DROP TABLE IF EXISTS "src_Monastery";
CREATE TABLE "src_Monastery" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Geographer";
CREATE TABLE "src_Geographer" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Work-of-Art";
CREATE TABLE "src_Work-of-Art" (c0 text);
DROP TABLE IF EXISTS "src_Ship";
CREATE TABLE "src_Ship" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Political-Region";
CREATE TABLE "src_Political-Region" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Fictional-Event";
CREATE TABLE "src_Fictional-Event" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Pope";
CREATE TABLE "src_Pope" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Legislation";
CREATE TABLE "src_Legislation" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Flavour";
CREATE TABLE "src_Flavour" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Train";
CREATE TABLE "src_Train" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Cultural-Organisation";
CREATE TABLE "src_Cultural-Organisation" (c0 text);
DROP TABLE IF EXISTS "src_Other-Religious-Person";
CREATE TABLE "src_Other-Religious-Person" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_exists";
CREATE TABLE "src_exists" (c0 text , c1 text , c2 text , c3 text);
DROP TABLE IF EXISTS "src_Person-Role";
CREATE TABLE "src_Person-Role" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Artefact";
CREATE TABLE "src_Artefact" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Cathedral";
CREATE TABLE "src_Cathedral" (c0 text);
DROP TABLE IF EXISTS "src_Intra-State-Group";
CREATE TABLE "src_Intra-State-Group" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Military-Organisation";
CREATE TABLE "src_Military-Organisation" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Professor";
CREATE TABLE "src_Professor" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Disease";
CREATE TABLE "src_Disease" (c0 text);
DROP TABLE IF EXISTS "src_Measurable-Trend";
CREATE TABLE "src_Measurable-Trend" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Board";
CREATE TABLE "src_Board" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Educational-Organisation";
CREATE TABLE "src_Educational-Organisation" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_League";
CREATE TABLE "src_League" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Geographical-Discovery";
CREATE TABLE "src_Geographical-Discovery" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Inventor";
CREATE TABLE "src_Inventor" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Language";
CREATE TABLE "src_Language" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Journalist";
CREATE TABLE "src_Journalist" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Abbey";
CREATE TABLE "src_Abbey" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Election";
CREATE TABLE "src_Election" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Person";
CREATE TABLE "src_Person" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Dancer";
CREATE TABLE "src_Dancer" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Object";
CREATE TABLE "src_Object" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_isLocationPartMemberOf";
CREATE TABLE "src_isLocationPartMemberOf" (c0 text , c1 text , c2 text , c3 text);
DROP TABLE IF EXISTS "src_Religious-Symbol";
CREATE TABLE "src_Religious-Symbol" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Leader";
CREATE TABLE "src_Leader" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Fictional-Person";
CREATE TABLE "src_Fictional-Person" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Economic-Process";
CREATE TABLE "src_Economic-Process" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Sportsman";
CREATE TABLE "src_Sportsman" (c0 text);
DROP TABLE IF EXISTS "src_Population-Movement";
CREATE TABLE "src_Population-Movement" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Art-Form";
CREATE TABLE "src_Art-Form" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Social-Stratum";
CREATE TABLE "src_Social-Stratum" (c0 text);
DROP TABLE IF EXISTS "src_hasCategory";
CREATE TABLE "src_hasCategory" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Vehicle";
CREATE TABLE "src_Vehicle" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Painting";
CREATE TABLE "src_Painting" (c0 text);
DROP TABLE IF EXISTS "src_VicodiOI";
CREATE TABLE "src_VicodiOI" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_related";
CREATE TABLE "src_related" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Religious-Ideology";
CREATE TABLE "src_Religious-Ideology" (c0 text);
DROP TABLE IF EXISTS "src_Composer";
CREATE TABLE "src_Composer" (c0 text);
DROP TABLE IF EXISTS "src_Artistic-Style";
CREATE TABLE "src_Artistic-Style" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Public-Oration";
CREATE TABLE "src_Public-Oration" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Head-of-Government";
CREATE TABLE "src_Head-of-Government" (c0 text);
DROP TABLE IF EXISTS "src_Church";
CREATE TABLE "src_Church" (c0 text);
DROP TABLE IF EXISTS "src_King";
CREATE TABLE "src_King" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Building";
CREATE TABLE "src_Building" (c0 text);
DROP TABLE IF EXISTS "src_Astronaut";
CREATE TABLE "src_Astronaut" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Geographical-Region";
CREATE TABLE "src_Geographical-Region" (c0 text);
DROP TABLE IF EXISTS "src_Ethnic-Group";
CREATE TABLE "src_Ethnic-Group" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Prince";
CREATE TABLE "src_Prince" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Secular-Movement";
CREATE TABLE "src_Secular-Movement" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Discoverer";
CREATE TABLE "src_Discoverer" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_International-Organisation";
CREATE TABLE "src_International-Organisation" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Period";
CREATE TABLE "src_Period" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Scandal";
CREATE TABLE "src_Scandal" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Physician";
CREATE TABLE "src_Physician" (c0 text);
DROP TABLE IF EXISTS "src_Relic";
CREATE TABLE "src_Relic" (c0 text);
DROP TABLE IF EXISTS "src_isRelationMemberOf";
CREATE TABLE "src_isRelationMemberOf" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Liturgical-Object";
CREATE TABLE "src_Liturgical-Object" (c0 text);
DROP TABLE IF EXISTS "src_Trades-Unionist";
CREATE TABLE "src_Trades-Unionist" (c0 text);
DROP TABLE IF EXISTS "src_Painter";
CREATE TABLE "src_Painter" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Water";
CREATE TABLE "src_Water" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_City";
CREATE TABLE "src_City" (c0 text , c1 text);
