DROP TABLE IF EXISTS "src_Abbey";
CREATE TABLE "src_Abbey" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_Armament";
CREATE TABLE "src_Armament" (c0 text);
DROP TABLE IF EXISTS "src_Author";
CREATE TABLE "src_Author" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_Business-Leader";
CREATE TABLE "src_Business-Leader" (c0 text);
DROP TABLE IF EXISTS "src_Settlement";
CREATE TABLE "src_Settlement" (c0 text);
DROP TABLE IF EXISTS "src_Country";
CREATE TABLE "src_Country" (c0 text);
DROP TABLE IF EXISTS "src_Cultural-Organisation";
CREATE TABLE "src_Cultural-Organisation" (c0 text);
DROP TABLE IF EXISTS "src_Social-Group";
CREATE TABLE "src_Social-Group" (c0 text);
DROP TABLE IF EXISTS "src_Symbol";
CREATE TABLE "src_Symbol" (c0 text);
DROP TABLE IF EXISTS "src_Head-of-State";
CREATE TABLE "src_Head-of-State" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_Intellectual-Construct";
CREATE TABLE "src_Intellectual-Construct" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_Geographer";
CREATE TABLE "src_Geographer" (c0 text);
DROP TABLE IF EXISTS "src_Secular-Leader";
CREATE TABLE "src_Secular-Leader" (c0 text);
DROP TABLE IF EXISTS "src_International-Organisation";
CREATE TABLE "src_International-Organisation" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_Language";
CREATE TABLE "src_Language" (c0 text);
DROP TABLE IF EXISTS "src_Measurable-Trend";
CREATE TABLE "src_Measurable-Trend" (c0 text);
DROP TABLE IF EXISTS "src_Newspaper";
CREATE TABLE "src_Newspaper" (c0 text);
DROP TABLE IF EXISTS "src_Work-of-Art";
CREATE TABLE "src_Work-of-Art" (c0 text);
DROP TABLE IF EXISTS "src_Person";
CREATE TABLE "src_Person" (c0 text);
DROP TABLE IF EXISTS "src_Political-Symbol";
CREATE TABLE "src_Political-Symbol" (c0 text);
DROP TABLE IF EXISTS "src_Publisher";
CREATE TABLE "src_Publisher" (c0 text);
DROP TABLE IF EXISTS "src_Religious-Movement";
CREATE TABLE "src_Religious-Movement" (c0 text);
DROP TABLE IF EXISTS "src_Scientific-Instrument";
CREATE TABLE "src_Scientific-Instrument" (c0 text);
DROP TABLE IF EXISTS "src_Structure";
CREATE TABLE "src_Structure" (c0 text);
DROP TABLE IF EXISTS "src_Trade-Association";
CREATE TABLE "src_Trade-Association" (c0 text);
DROP TABLE IF EXISTS "src_University";
CREATE TABLE "src_University" (c0 text, c1 text, c2 text);
DROP TABLE IF EXISTS "src_hasLocationPartMember";
CREATE TABLE "src_hasLocationPartMember" (c0 text, c1 text);

