DROP TABLE IF EXISTS "src_Abbey";
CREATE TABLE "src_Abbey" (c0 text);
DROP TABLE IF EXISTS "src_Natural-Object";
CREATE TABLE "src_Natural-Object" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_Artistic-Style";
CREATE TABLE "src_Artistic-Style" (c0 text);
DROP TABLE IF EXISTS "src_Management-Organisation";
CREATE TABLE "src_Management-Organisation" (c0 text);
DROP TABLE IF EXISTS "src_Category";
CREATE TABLE "src_Category" (c0 text);
DROP TABLE IF EXISTS "src_City";
CREATE TABLE "src_City" (c0 text);
DROP TABLE IF EXISTS "src_Clothing";
CREATE TABLE "src_Clothing" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_Organisation";
CREATE TABLE "src_Organisation" (c0 text);
DROP TABLE IF EXISTS "src_Disease";
CREATE TABLE "src_Disease" (c0 text);
DROP TABLE IF EXISTS "src_Symbol";
CREATE TABLE "src_Symbol" (c0 text);
DROP TABLE IF EXISTS "src_Emperor";
CREATE TABLE "src_Emperor" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_Intellectual-Construct";
CREATE TABLE "src_Intellectual-Construct" (c0 text);
DROP TABLE IF EXISTS "src_FuzzyTemporalInterval";
CREATE TABLE "src_FuzzyTemporalInterval" (c0 text);
DROP TABLE IF EXISTS "src_Geographical-Region";
CREATE TABLE "src_Geographical-Region" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_Life-Event";
CREATE TABLE "src_Life-Event" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_Jurist";
CREATE TABLE "src_Jurist" (c0 text);
DROP TABLE IF EXISTS "src_Legislation";
CREATE TABLE "src_Legislation" (c0 text);
DROP TABLE IF EXISTS "src_Military-Organisation";
CREATE TABLE "src_Military-Organisation" (c0 text);
DROP TABLE IF EXISTS "src_Other-Religious-Person";
CREATE TABLE "src_Other-Religious-Person" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_Role";
CREATE TABLE "src_Role" (c0 text);
DROP TABLE IF EXISTS "src_Politician";
CREATE TABLE "src_Politician" (c0 text);
DROP TABLE IF EXISTS "src_Public-Oration";
CREATE TABLE "src_Public-Oration" (c0 text);
DROP TABLE IF EXISTS "src_Religious-Symbol";
CREATE TABLE "src_Religious-Symbol" (c0 text);
DROP TABLE IF EXISTS "src_Ship";
CREATE TABLE "src_Ship" (c0 text);
DROP TABLE IF EXISTS "src_Theologian";
CREATE TABLE "src_Theologian" (c0 text);
DROP TABLE IF EXISTS "src_Treaty";
CREATE TABLE "src_Treaty" (c0 text);
DROP TABLE IF EXISTS "src_exists";
CREATE TABLE "src_exists" (c0 text, c1 text, c2 text);
DROP TABLE IF EXISTS "src_isRelationMemberOf";
CREATE TABLE "src_isRelationMemberOf" (c0 text);

