PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX : <http://benchmark/OWL2Bench#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?0 
WHERE {
	?0  rdf:type  :Student. 
	?1 rdf:type  :Organization.  
	?1  :hasDean  ?2.  
	?2  :teachesCourse  ?3.  
	?0 :takesCourse  ?3 .
}
