DROP TABLE IF EXISTS "src_LightweightFoldable_Wheelchair";
CREATE TABLE "src_LightweightFoldable_Wheelchair" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Guillaume_Barre";
CREATE TABLE "src_Guillaume_Barre" (c0 text);
DROP TABLE IF EXISTS "src_isAffectedBy";
CREATE TABLE "src_isAffectedBy" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_isAssistedBy";
CREATE TABLE "src_isAssistedBy" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_UpperLimbMobility";
CREATE TABLE "src_UpperLimbMobility" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_FaceToFaceCommunicationDevice";
CREATE TABLE "src_FaceToFaceCommunicationDevice" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Ability";
CREATE TABLE "src_Ability" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Disability";
CREATE TABLE "src_Disability" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_See_partially";
CREATE TABLE "src_See_partially" (c0 text);
DROP TABLE IF EXISTS "src_SensoryAbility";
CREATE TABLE "src_SensoryAbility" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_BrailleAlarmClock";
CREATE TABLE "src_BrailleAlarmClock" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Autism";
CREATE TABLE "src_Autism" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_FaceToFaceCommunicationSoftware";
CREATE TABLE "src_FaceToFaceCommunicationSoftware" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_LowerLimbMobility";
CREATE TABLE "src_LowerLimbMobility" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Lightweight_Wheelchair";
CREATE TABLE "src_Lightweight_Wheelchair" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_requiresAbility";
CREATE TABLE "src_requiresAbility" (c0 text , c1 text , c2 text , c3 text);
DROP TABLE IF EXISTS "src_BraillePillOrganiser";
CREATE TABLE "src_BraillePillOrganiser" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_ListenDevice";
CREATE TABLE "src_ListenDevice" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_SymbolBoard";
CREATE TABLE "src_SymbolBoard" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Scoliosis";
CREATE TABLE "src_Scoliosis" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_affects";
CREATE TABLE "src_affects" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_assistsWith";
CREATE TABLE "src_assistsWith" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_MobilityDevice";
CREATE TABLE "src_MobilityDevice" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_SpeechDisability";
CREATE TABLE "src_SpeechDisability" (c0 text);
DROP TABLE IF EXISTS "src_Hear_partially";
CREATE TABLE "src_Hear_partially" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_IntellectualDisability";
CREATE TABLE "src_IntellectualDisability" (c0 text);
DROP TABLE IF EXISTS "src_TactileReading";
CREATE TABLE "src_TactileReading" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_HearingAbility";
CREATE TABLE "src_HearingAbility" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Cerebral_palsy";
CREATE TABLE "src_Cerebral_palsy" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Poliomyelitis";
CREATE TABLE "src_Poliomyelitis" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Multiple_sclerosis";
CREATE TABLE "src_Multiple_sclerosis" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_HearingDisability";
CREATE TABLE "src_HearingDisability" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_LowVision";
CREATE TABLE "src_LowVision" (c0 text);
DROP TABLE IF EXISTS "src_SpeechAbility";
CREATE TABLE "src_SpeechAbility" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Spina_Bifida";
CREATE TABLE "src_Spina_Bifida" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Achondroplasia";
CREATE TABLE "src_Achondroplasia" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Kyphosis";
CREATE TABLE "src_Kyphosis" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Thing";
CREATE TABLE "src_Thing" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Wheelchair";
CREATE TABLE "src_Wheelchair" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_See";
CREATE TABLE "src_See" (c0 text);
DROP TABLE IF EXISTS "src_Little_or_No_Speech";
CREATE TABLE "src_Little_or_No_Speech" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Epilepsy";
CREATE TABLE "src_Epilepsy" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Quadriplegia";
CREATE TABLE "src_Quadriplegia" (c0 text);
DROP TABLE IF EXISTS "src_ReadingDevice";
CREATE TABLE "src_ReadingDevice" (c0 text);
DROP TABLE IF EXISTS "src_Talking_Thermometer";
CREATE TABLE "src_Talking_Thermometer" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_VisualDisability";
CREATE TABLE "src_VisualDisability" (c0 text);
DROP TABLE IF EXISTS "src_Communication_Device";
CREATE TABLE "src_Communication_Device" (c0 text);
DROP TABLE IF EXISTS "src_PhysicalDisability";
CREATE TABLE "src_PhysicalDisability" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_PhysicalAbility";
CREATE TABLE "src_PhysicalAbility" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Motorised_Wheelchair";
CREATE TABLE "src_Motorised_Wheelchair" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_LimbMobility";
CREATE TABLE "src_LimbMobility" (c0 text);
DROP TABLE IF EXISTS "src_Amputation";
CREATE TABLE "src_Amputation" (c0 text);
DROP TABLE IF EXISTS "src_SpeechDevice";
CREATE TABLE "src_SpeechDevice" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Paraplegia";
CREATE TABLE "src_Paraplegia" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_TelephoneAid";
CREATE TABLE "src_TelephoneAid" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_TactileAbility";
CREATE TABLE "src_TactileAbility" (c0 text);
DROP TABLE IF EXISTS "src_Deafened";
CREATE TABLE "src_Deafened" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_AssistiveDevice";
CREATE TABLE "src_AssistiveDevice" (c0 text);
DROP TABLE IF EXISTS "src_Hard_of_hearing";
CREATE TABLE "src_Hard_of_hearing" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Osteogensis_Imperfecta";
CREATE TABLE "src_Osteogensis_Imperfecta" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_TalkingReading";
CREATE TABLE "src_TalkingReading" (c0 text);
DROP TABLE IF EXISTS "src_Reach";
CREATE TABLE "src_Reach" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_BrailleWatch";
CREATE TABLE "src_BrailleWatch" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_BrailleWritingDevice";
CREATE TABLE "src_BrailleWritingDevice" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Blind";
CREATE TABLE "src_Blind" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_MovementAbility";
CREATE TABLE "src_MovementAbility" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Manual_Wheelchair";
CREATE TABLE "src_Manual_Wheelchair" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Hemiplegia";
CREATE TABLE "src_Hemiplegia" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Stuttering";
CREATE TABLE "src_Stuttering" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_BatteryPowered_Wheelchair";
CREATE TABLE "src_BatteryPowered_Wheelchair" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Dystonia";
CREATE TABLE "src_Dystonia" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_WritingDevice";
CREATE TABLE "src_WritingDevice" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Hear";
CREATE TABLE "src_Hear" (c0 text);
DROP TABLE IF EXISTS "src_Muscular_dystrophy";
CREATE TABLE "src_Muscular_dystrophy" (c0 text);
DROP TABLE IF EXISTS "src_Foldable_Wheelchair";
CREATE TABLE "src_Foldable_Wheelchair" (c0 text);
DROP TABLE IF EXISTS "src_Deaf";
CREATE TABLE "src_Deaf" (c0 text);
DROP TABLE IF EXISTS "src_MentalDisability";
CREATE TABLE "src_MentalDisability" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_SightAbility";
CREATE TABLE "src_SightAbility" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Device";
CREATE TABLE "src_Device" (c0 text , c1 text);
