version: '2'
services:
  db:
    image: postgres:11
    restart: always
  framework:
    build: ./
    environment:
      PGHOST: db
    volumes:
      - ./logs:/logs
    depends_on:
      - db
    links:
      - db
