version: '3'
services:
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
  converters:
    build: ./OBDAconverter
  framework:
    build: ./OBDAframework
    environment:
      PGUSER: ${PG_USER}
      PGHOST: db
      PGPASSWORD: ${PG_PASSWORD}
      PGDATABASE: ${PG_DB}
      PGPORT: ${PG_PORT}
    depends_on:
      - db
    links:
      - db
      - converters
