DROP TABLE IF EXISTS "MovementAbility";
CREATE TABLE "MovementAbility" (c0 text);
INSERT INTO "MovementAbility" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "PhysicalAbility";
CREATE TABLE "PhysicalAbility" (c0 text);
INSERT INTO "PhysicalAbility" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Stuttering";
CREATE TABLE "Stuttering" (c0 text);
INSERT INTO "Stuttering" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "SpeechDisability";
CREATE TABLE "SpeechDisability" (c0 text);
INSERT INTO "SpeechDisability" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "LowerLimbMobility";
CREATE TABLE "LowerLimbMobility" (c0 text);
INSERT INTO "LowerLimbMobility" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "LimbMobility";
CREATE TABLE "LimbMobility" (c0 text);
INSERT INTO "LimbMobility" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "FaceToFaceCommunicationDevice";
CREATE TABLE "FaceToFaceCommunicationDevice" (c0 text);
INSERT INTO "FaceToFaceCommunicationDevice" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Communication_Device";
CREATE TABLE "Communication_Device" (c0 text);
INSERT INTO "Communication_Device" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "assistsWith";
CREATE TABLE "assistsWith" (c0 text, c1 text);
INSERT INTO "assistsWith" SELECT MD5(random()::text), MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "SpeechAbility";
CREATE TABLE "SpeechAbility" (c0 text);
INSERT INTO "SpeechAbility" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "WritingDevice";
CREATE TABLE "WritingDevice" (c0 text);
INSERT INTO "WritingDevice" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Multiple_sclerosis";
CREATE TABLE "Multiple_sclerosis" (c0 text);
INSERT INTO "Multiple_sclerosis" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "PhysicalDisability";
CREATE TABLE "PhysicalDisability" (c0 text);
INSERT INTO "PhysicalDisability" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Achondroplasia";
CREATE TABLE "Achondroplasia" (c0 text);
INSERT INTO "Achondroplasia" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "BraillePillOrganiser";
CREATE TABLE "BraillePillOrganiser" (c0 text);
INSERT INTO "BraillePillOrganiser" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "TactileReading";
CREATE TABLE "TactileReading" (c0 text);
INSERT INTO "TactileReading" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "TelephoneAid";
CREATE TABLE "TelephoneAid" (c0 text);
INSERT INTO "TelephoneAid" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "ListenDevice";
CREATE TABLE "ListenDevice" (c0 text);
INSERT INTO "ListenDevice" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "SpeechDevice";
CREATE TABLE "SpeechDevice" (c0 text);
INSERT INTO "SpeechDevice" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "MentalDisability";
CREATE TABLE "MentalDisability" (c0 text);
INSERT INTO "MentalDisability" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Disability";
CREATE TABLE "Disability" (c0 text);
INSERT INTO "Disability" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "BatteryPowered_Wheelchair";
CREATE TABLE "BatteryPowered_Wheelchair" (c0 text);
INSERT INTO "BatteryPowered_Wheelchair" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Motorised_Wheelchair";
CREATE TABLE "Motorised_Wheelchair" (c0 text);
INSERT INTO "Motorised_Wheelchair" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Hear";
CREATE TABLE "Hear" (c0 text);
INSERT INTO "Hear" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "HearingAbility";
CREATE TABLE "HearingAbility" (c0 text);
INSERT INTO "HearingAbility" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Muscular_dystrophy";
CREATE TABLE "Muscular_dystrophy" (c0 text);
INSERT INTO "Muscular_dystrophy" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Wheelchair";
CREATE TABLE "Wheelchair" (c0 text);
INSERT INTO "Wheelchair" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "MobilityDevice";
CREATE TABLE "MobilityDevice" (c0 text);
INSERT INTO "MobilityDevice" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Paraplegia";
CREATE TABLE "Paraplegia" (c0 text);
INSERT INTO "Paraplegia" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "affects";
CREATE TABLE "affects" (c0 text, c1 text);
INSERT INTO "affects" SELECT MD5(random()::text), MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "See";
CREATE TABLE "See" (c0 text);
INSERT INTO "See" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "SightAbility";
CREATE TABLE "SightAbility" (c0 text);
INSERT INTO "SightAbility" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "BrailleAlarmClock";
CREATE TABLE "BrailleAlarmClock" (c0 text);
INSERT INTO "BrailleAlarmClock" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Hear_partially";
CREATE TABLE "Hear_partially" (c0 text);
INSERT INTO "Hear_partially" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "AssistiveDevice";
CREATE TABLE "AssistiveDevice" (c0 text);
INSERT INTO "AssistiveDevice" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "UpperLimbMobility";
CREATE TABLE "UpperLimbMobility" (c0 text);
INSERT INTO "UpperLimbMobility" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "SensoryAbility";
CREATE TABLE "SensoryAbility" (c0 text);
INSERT INTO "SensoryAbility" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Ability";
CREATE TABLE "Ability" (c0 text);
INSERT INTO "Ability" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "LowVision";
CREATE TABLE "LowVision" (c0 text);
INSERT INTO "LowVision" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "VisualDisability";
CREATE TABLE "VisualDisability" (c0 text);
INSERT INTO "VisualDisability" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Talking_Thermometer";
CREATE TABLE "Talking_Thermometer" (c0 text);
INSERT INTO "Talking_Thermometer" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "TalkingReading";
CREATE TABLE "TalkingReading" (c0 text);
INSERT INTO "TalkingReading" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "ReadingDevice";
CREATE TABLE "ReadingDevice" (c0 text);
INSERT INTO "ReadingDevice" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "requiresAbility";
CREATE TABLE "requiresAbility" (c0 text, c1 text);
INSERT INTO "requiresAbility" SELECT MD5(random()::text), MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Epilepsy";
CREATE TABLE "Epilepsy" (c0 text);
INSERT INTO "Epilepsy" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "IntellectualDisability";
CREATE TABLE "IntellectualDisability" (c0 text);
INSERT INTO "IntellectualDisability" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Autism";
CREATE TABLE "Autism" (c0 text);
INSERT INTO "Autism" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Amputation";
CREATE TABLE "Amputation" (c0 text);
INSERT INTO "Amputation" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Device";
CREATE TABLE "Device" (c0 text);
INSERT INTO "Device" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Manual_Wheelchair";
CREATE TABLE "Manual_Wheelchair" (c0 text);
INSERT INTO "Manual_Wheelchair" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "BrailleWatch";
CREATE TABLE "BrailleWatch" (c0 text);
INSERT INTO "BrailleWatch" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Foldable_Wheelchair";
CREATE TABLE "Foldable_Wheelchair" (c0 text);
INSERT INTO "Foldable_Wheelchair" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Osteogensis_Imperfecta";
CREATE TABLE "Osteogensis_Imperfecta" (c0 text);
INSERT INTO "Osteogensis_Imperfecta" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Hemiplegia";
CREATE TABLE "Hemiplegia" (c0 text);
INSERT INTO "Hemiplegia" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Quadriplegia";
CREATE TABLE "Quadriplegia" (c0 text);
INSERT INTO "Quadriplegia" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Guillaume_Barre";
CREATE TABLE "Guillaume_Barre" (c0 text);
INSERT INTO "Guillaume_Barre" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "BrailleWritingDevice";
CREATE TABLE "BrailleWritingDevice" (c0 text);
INSERT INTO "BrailleWritingDevice" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "See_partially";
CREATE TABLE "See_partially" (c0 text);
INSERT INTO "See_partially" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Spina_Bifida";
CREATE TABLE "Spina_Bifida" (c0 text);
INSERT INTO "Spina_Bifida" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "TactileAbility";
CREATE TABLE "TactileAbility" (c0 text);
INSERT INTO "TactileAbility" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Thing";
CREATE TABLE "Thing" (c0 text);
INSERT INTO "Thing" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "isAssistedBy";
CREATE TABLE "isAssistedBy" (c0 text, c1 text);
INSERT INTO "isAssistedBy" SELECT MD5(random()::text), MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "isAffectedBy";
CREATE TABLE "isAffectedBy" (c0 text, c1 text);
INSERT INTO "isAffectedBy" SELECT MD5(random()::text), MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "LightweightFoldable_Wheelchair";
CREATE TABLE "LightweightFoldable_Wheelchair" (c0 text);
INSERT INTO "LightweightFoldable_Wheelchair" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Lightweight_Wheelchair";
CREATE TABLE "Lightweight_Wheelchair" (c0 text);
INSERT INTO "Lightweight_Wheelchair" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Blind";
CREATE TABLE "Blind" (c0 text);
INSERT INTO "Blind" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Reach";
CREATE TABLE "Reach" (c0 text);
INSERT INTO "Reach" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Deaf";
CREATE TABLE "Deaf" (c0 text);
INSERT INTO "Deaf" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "HearingDisability";
CREATE TABLE "HearingDisability" (c0 text);
INSERT INTO "HearingDisability" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Deafened";
CREATE TABLE "Deafened" (c0 text);
INSERT INTO "Deafened" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "SymbolBoard";
CREATE TABLE "SymbolBoard" (c0 text);
INSERT INTO "SymbolBoard" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Dystonia";
CREATE TABLE "Dystonia" (c0 text);
INSERT INTO "Dystonia" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "FaceToFaceCommunicationSoftware";
CREATE TABLE "FaceToFaceCommunicationSoftware" (c0 text);
INSERT INTO "FaceToFaceCommunicationSoftware" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Kyphosis";
CREATE TABLE "Kyphosis" (c0 text);
INSERT INTO "Kyphosis" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Hard_of_hearing";
CREATE TABLE "Hard_of_hearing" (c0 text);
INSERT INTO "Hard_of_hearing" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Cerebral_palsy";
CREATE TABLE "Cerebral_palsy" (c0 text);
INSERT INTO "Cerebral_palsy" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Poliomyelitis";
CREATE TABLE "Poliomyelitis" (c0 text);
INSERT INTO "Poliomyelitis" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Little_or_No_Speech";
CREATE TABLE "Little_or_No_Speech" (c0 text);
INSERT INTO "Little_or_No_Speech" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Scoliosis";
CREATE TABLE "Scoliosis" (c0 text);
INSERT INTO "Scoliosis" SELECT MD5(random()::text) FROM generate_series(1, 10);