PREFIX : <http://example.com/example.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT DISTINCT ?0 ?1 ?2 WHERE {
  ?0 rdf:type :FinantialInstrument;
    :belongsToCompany ?1.
  ?1 rdf:type :Company;
    :hasStock ?2.
  ?2 rdf:type :Stock.
}