CREATE TABLE "AdministrativeStaff" (c0 text);
CREATE TABLE "Employee" (c0 text);
CREATE TABLE "advisor" (c0 text, c1 text);
CREATE TABLE "Person" (c0 text);
CREATE TABLE "Professor" (c0 text);
CREATE TABLE "affiliatedOrganizationOf" (c0 text, c1 text);
CREATE TABLE "Organization" (c0 text);
CREATE TABLE "affiliateOf" (c0 text, c1 text);
CREATE TABLE "age" (c0 text, c1 text);
CREATE TABLE "Article" (c0 text);
CREATE TABLE "Publication" (c0 text);
CREATE TABLE "AssistantProfessor" (c0 text);
CREATE TABLE "AssociateProfessor" (c0 text);
CREATE TABLE "Book" (c0 text);
CREATE TABLE "Chair" (c0 text);
CREATE TABLE "headOf" (c0 text, c1 text);
CREATE TABLE "Department" (c0 text);
CREATE TABLE "ClericalStaff" (c0 text);
CREATE TABLE "College" (c0 text);
CREATE TABLE "ConferencePaper" (c0 text);
CREATE TABLE "Course" (c0 text);
CREATE TABLE "Work" (c0 text);
CREATE TABLE "Dean" (c0 text);
CREATE TABLE "degreeFrom" (c0 text, c1 text);
CREATE TABLE "University" (c0 text);
CREATE TABLE "hasAlumnus" (c0 text, c1 text);
CREATE TABLE "Director" (c0 text);
CREATE TABLE "Program" (c0 text);
CREATE TABLE "doctoralDegreeFrom" (c0 text, c1 text);
CREATE TABLE "emailAddress" (c0 text, c1 text);
CREATE TABLE "worksFor" (c0 text, c1 text);
CREATE TABLE "Faculty" (c0 text);
CREATE TABLE "FullProfessor" (c0 text);
CREATE TABLE "GraduateCourse" (c0 text);
CREATE TABLE "GraduateStudent" (c0 text);
CREATE TABLE "takesCourse" (c0 text, c1 text);
CREATE TABLE "Institute" (c0 text);
CREATE TABLE "JournalArticle" (c0 text);
CREATE TABLE "Lecturer" (c0 text);
CREATE TABLE "listedCourse" (c0 text, c1 text);
CREATE TABLE "Schedule" (c0 text);
CREATE TABLE "Manual" (c0 text);
CREATE TABLE "mastersDegreeFrom" (c0 text, c1 text);
CREATE TABLE "member" (c0 text, c1 text);
CREATE TABLE "memberOf" (c0 text, c1 text);
CREATE TABLE "orgPublication" (c0 text, c1 text);
CREATE TABLE "PostDoc" (c0 text);
CREATE TABLE "publicationAuthor" (c0 text, c1 text);
CREATE TABLE "publicationDate" (c0 text, c1 text);
CREATE TABLE "publicationResearch" (c0 text, c1 text);
CREATE TABLE "Research" (c0 text);
CREATE TABLE "ResearchAssistant" (c0 text);
CREATE TABLE "ResearchGroup" (c0 text);
CREATE TABLE "researchProject" (c0 text, c1 text);
CREATE TABLE "Software" (c0 text);
CREATE TABLE "softwareDocumentation" (c0 text, c1 text);
CREATE TABLE "softwareVersion" (c0 text, c1 text);
CREATE TABLE "Specification" (c0 text);
CREATE TABLE "Student" (c0 text);
CREATE TABLE "subOrganizationOf" (c0 text, c1 text);
CREATE TABLE "SystemsStaff" (c0 text);
CREATE TABLE "teacherOf" (c0 text, c1 text);
CREATE TABLE "TeachingAssistant" (c0 text);
CREATE TABLE "teachingAssistantOf" (c0 text, c1 text);
CREATE TABLE "TechnicalReport" (c0 text);
CREATE TABLE "telephone" (c0 text, c1 text);
CREATE TABLE "tenured" (c0 text, c1 text);
CREATE TABLE "title" (c0 text, c1 text);
CREATE TABLE "undergraduateDegreeFrom" (c0 text, c1 text);
CREATE TABLE "UndergraduateStudent" (c0 text);
CREATE TABLE "UnofficialPublication" (c0 text);
CREATE TABLE "VisitingProfessor" (c0 text);