PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ub: <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#>
SELECT ?0 ?1 ?3
WHERE { 
  ?0 rdf:type ub:GraduateStudent .
  ?1 rdf:type ub:University .
  ?3 rdf:type ub:Department .
  ?0 ub:memberOf ?3 .
  ?3 ub:subOrganizationOf ?1 .
  ?0 ub:undergraduateDegreeFrom ?1
}