PREFIX : <http://www.movieontology.org/2009/11/09/movieontology.owl#>
PREFIX dbpedia: <http://dbpedia.org/ontology/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT $x
WHERE { 
   $x a :Actress. $x dbpedia:birthName "Pfeiffer, Michelle"
}