PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX : <http://example.com/example.owl#>
SELECT DISTINCT ?0 ?1
WHERE
{
	?2 :enginevnm12nl0ce2 ?0 .
	?0 :settlevh8nl0ce1 ?1 .
	?3 :delicatevi38nl0ce1 ?0
}
