DROP TABLE IF EXISTS "src_AssistantProfessor";
CREATE TABLE "src_AssistantProfessor" (c0 text);
DROP TABLE IF EXISTS "src_AssociateProfessor";
CREATE TABLE "src_AssociateProfessor" (c0 text);
DROP TABLE IF EXISTS "src_Course";
CREATE TABLE "src_Course" (c0 text);
DROP TABLE IF EXISTS "src_Department";
CREATE TABLE "src_Department" (c0 text);
DROP TABLE IF EXISTS "src_FullProfessor";
CREATE TABLE "src_FullProfessor" (c0 text);
DROP TABLE IF EXISTS "src_GraduateCourse";
CREATE TABLE "src_GraduateCourse" (c0 text);
DROP TABLE IF EXISTS "src_GraduateStudent";
CREATE TABLE "src_GraduateStudent" (c0 text);
DROP TABLE IF EXISTS "src_Lecturer";
CREATE TABLE "src_Lecturer" (c0 text);
DROP TABLE IF EXISTS "src_Publication";
CREATE TABLE "src_Publication" (c0 text);
DROP TABLE IF EXISTS "src_ResearchAssistant";
CREATE TABLE "src_ResearchAssistant" (c0 text);
DROP TABLE IF EXISTS "src_ResearchGroup";
CREATE TABLE "src_ResearchGroup" (c0 text);
DROP TABLE IF EXISTS "src_TeachingAssistant";
CREATE TABLE "src_TeachingAssistant" (c0 text);
DROP TABLE IF EXISTS "src_UndergraduateStudent";
CREATE TABLE "src_UndergraduateStudent" (c0 text);
DROP TABLE IF EXISTS "src_University";
CREATE TABLE "src_University" (c0 text);
DROP TABLE IF EXISTS "src_advisor";
CREATE TABLE "src_advisor" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_doctoralDegreeFrom";
CREATE TABLE "src_doctoralDegreeFrom" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_emailAddress";
CREATE TABLE "src_emailAddress" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_headOf";
CREATE TABLE "src_headOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_mastersDegreeFrom";
CREATE TABLE "src_mastersDegreeFrom" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_memberOf";
CREATE TABLE "src_memberOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_name";
CREATE TABLE "src_name" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_publicationAuthor";
CREATE TABLE "src_publicationAuthor" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_researchInterest";
CREATE TABLE "src_researchInterest" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_subOrganizationOf";
CREATE TABLE "src_subOrganizationOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_takesCourse";
CREATE TABLE "src_takesCourse" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_teacherOf";
CREATE TABLE "src_teacherOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_teachingAssistantOf";
CREATE TABLE "src_teachingAssistantOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_telephone";
CREATE TABLE "src_telephone" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_undergraduateDegreeFrom";
CREATE TABLE "src_undergraduateDegreeFrom" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_worksFor";
CREATE TABLE "src_worksFor" (c0 text, c1 text);