DROP TABLE IF EXISTS "src_AdministrativeStaff";
CREATE TABLE "src_AdministrativeStaff" (c0 text);
DROP TABLE IF EXISTS "src_Article";
CREATE TABLE "src_Article" (c0 text);
DROP TABLE IF EXISTS "src_AssistantProfessor";
CREATE TABLE "src_AssistantProfessor" (c0 text);
DROP TABLE IF EXISTS "src_AssociateProfessor";
CREATE TABLE "src_AssociateProfessor" (c0 text);
DROP TABLE IF EXISTS "src_Book";
CREATE TABLE "src_Book" (c0 text);
DROP TABLE IF EXISTS "src_Chair";
CREATE TABLE "src_Chair" (c0 text);
DROP TABLE IF EXISTS "src_ClericalStaff";
CREATE TABLE "src_ClericalStaff" (c0 text);
DROP TABLE IF EXISTS "src_College";
CREATE TABLE "src_College" (c0 text);
DROP TABLE IF EXISTS "src_ConferencePaper";
CREATE TABLE "src_ConferencePaper" (c0 text);
DROP TABLE IF EXISTS "src_Course";
CREATE TABLE "src_Course" (c0 text);
DROP TABLE IF EXISTS "src_Dean";
CREATE TABLE "src_Dean" (c0 text);
DROP TABLE IF EXISTS "src_Department";
CREATE TABLE "src_Department" (c0 text);
DROP TABLE IF EXISTS "src_Director";
CREATE TABLE "src_Director" (c0 text);
DROP TABLE IF EXISTS "src_Employee";
CREATE TABLE "src_Employee" (c0 text);
DROP TABLE IF EXISTS "src_Faculty";
CREATE TABLE "src_Faculty" (c0 text);
DROP TABLE IF EXISTS "src_FullProfessor";
CREATE TABLE "src_FullProfessor" (c0 text);
DROP TABLE IF EXISTS "src_GraduateCourse";
CREATE TABLE "src_GraduateCourse" (c0 text);
DROP TABLE IF EXISTS "src_GraduateStudent";
CREATE TABLE "src_GraduateStudent" (c0 text);
DROP TABLE IF EXISTS "src_Institute";
CREATE TABLE "src_Institute" (c0 text);
DROP TABLE IF EXISTS "src_JournalArticle";
CREATE TABLE "src_JournalArticle" (c0 text);
DROP TABLE IF EXISTS "src_Lecturer";
CREATE TABLE "src_Lecturer" (c0 text);
DROP TABLE IF EXISTS "src_Manual";
CREATE TABLE "src_Manual" (c0 text);
DROP TABLE IF EXISTS "src_Organization";
CREATE TABLE "src_Organization" (c0 text);
DROP TABLE IF EXISTS "src_Person";
CREATE TABLE "src_Person" (c0 text);
DROP TABLE IF EXISTS "src_PostDoc";
CREATE TABLE "src_PostDoc" (c0 text);
DROP TABLE IF EXISTS "src_Professor";
CREATE TABLE "src_Professor" (c0 text);
DROP TABLE IF EXISTS "src_Program";
CREATE TABLE "src_Program" (c0 text);
DROP TABLE IF EXISTS "src_Publication";
CREATE TABLE "src_Publication" (c0 text);
DROP TABLE IF EXISTS "src_Research";
CREATE TABLE "src_Research" (c0 text);
DROP TABLE IF EXISTS "src_ResearchAssistant";
CREATE TABLE "src_ResearchAssistant" (c0 text);
DROP TABLE IF EXISTS "src_ResearchGroup";
CREATE TABLE "src_ResearchGroup" (c0 text);
DROP TABLE IF EXISTS "src_Schedule";
CREATE TABLE "src_Schedule" (c0 text);
DROP TABLE IF EXISTS "src_Software";
CREATE TABLE "src_Software" (c0 text);
DROP TABLE IF EXISTS "src_Specification";
CREATE TABLE "src_Specification" (c0 text);
DROP TABLE IF EXISTS "src_Student";
CREATE TABLE "src_Student" (c0 text);
DROP TABLE IF EXISTS "src_SystemsStaff";
CREATE TABLE "src_SystemsStaff" (c0 text);
DROP TABLE IF EXISTS "src_TeachingAssistant";
CREATE TABLE "src_TeachingAssistant" (c0 text);
DROP TABLE IF EXISTS "src_TechnicalReport";
CREATE TABLE "src_TechnicalReport" (c0 text);
DROP TABLE IF EXISTS "src_UndergraduateStudent";
CREATE TABLE "src_UndergraduateStudent" (c0 text);
DROP TABLE IF EXISTS "src_University";
CREATE TABLE "src_University" (c0 text);
DROP TABLE IF EXISTS "src_UnofficialPublication";
CREATE TABLE "src_UnofficialPublication" (c0 text);
DROP TABLE IF EXISTS "src_VisitingProfessor";
CREATE TABLE "src_VisitingProfessor" (c0 text);
DROP TABLE IF EXISTS "src_Work";
CREATE TABLE "src_Work" (c0 text);
DROP TABLE IF EXISTS "src_age";
CREATE TABLE "src_age" (c0 text, c1 integer);
DROP TABLE IF EXISTS "src_advisor";
CREATE TABLE "src_advisor" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_affiliateOf";
CREATE TABLE "src_affiliateOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_affiliatedOrganizationOf";
CREATE TABLE "src_affiliatedOrganizationOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_degreeFrom";
CREATE TABLE "src_degreeFrom" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_doctoralDegreeFrom";
CREATE TABLE "src_doctoralDegreeFrom" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_emailAddress";
CREATE TABLE "src_emailAddress" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_hasAlumnus";
CREATE TABLE "src_hasAlumnus" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_headOf";
CREATE TABLE "src_headOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_listedCourse";
CREATE TABLE "src_listedCourse" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_mastersDegreeFrom";
CREATE TABLE "src_mastersDegreeFrom" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_member";
CREATE TABLE "src_member" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_memberOf";
CREATE TABLE "src_memberOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_name";
CREATE TABLE "src_name" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_orgPublication";
CREATE TABLE "src_orgPublication" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_publicationAuthor";
CREATE TABLE "src_publicationAuthor" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_publicationDate";
CREATE TABLE "src_publicationDate" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_publicationResearch";
CREATE TABLE "src_publicationResearch" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_researchInterest";
CREATE TABLE "src_researchInterest" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_researchProject";
CREATE TABLE "src_researchProject" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_softwareDocumentation";
CREATE TABLE "src_softwareDocumentation" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_softwareVersion";
CREATE TABLE "src_softwareVersion" (c0 text, c1 integer);
DROP TABLE IF EXISTS "src_subOrganizationOf";
CREATE TABLE "src_subOrganizationOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_takesCourse";
CREATE TABLE "src_takesCourse" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_teacherOf";
CREATE TABLE "src_teacherOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_teachingAssistantOf";
CREATE TABLE "src_teachingAssistantOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_telephone";
CREATE TABLE "src_telephone" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_tenured";
CREATE TABLE "src_tenured" (c0 text, c1 integer);
DROP TABLE IF EXISTS "src_title";
CREATE TABLE "src_title" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_undergraduateDegreeFrom";
CREATE TABLE "src_undergraduateDegreeFrom" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_worksFor";
CREATE TABLE "src_worksFor" (c0 text, c1 text);