DROP TABLE IF EXISTS "AeronauticalEngineering";
CREATE TABLE "AeronauticalEngineering" (c0 text);
DROP TABLE IF EXISTS "Engineering";
CREATE TABLE "Engineering" (c0 text);
DROP TABLE IF EXISTS "Anthropology";
CREATE TABLE "Anthropology" (c0 text);
DROP TABLE IF EXISTS "HumanitiesAndSocial";
CREATE TABLE "HumanitiesAndSocial" (c0 text);
DROP TABLE IF EXISTS "Architecture";
CREATE TABLE "Architecture" (c0 text);
DROP TABLE IF EXISTS "FineArts";
CREATE TABLE "FineArts" (c0 text);
DROP TABLE IF EXISTS "Article";
CREATE TABLE "Article" (c0 text);
DROP TABLE IF EXISTS "Publication";
CREATE TABLE "Publication" (c0 text);
DROP TABLE IF EXISTS "AsianArts";
CREATE TABLE "AsianArts" (c0 text);
DROP TABLE IF EXISTS "AssistantProfessor";
CREATE TABLE "AssistantProfessor" (c0 text);
DROP TABLE IF EXISTS "Professor";
CREATE TABLE "Professor" (c0 text);
DROP TABLE IF EXISTS "AssociateProfessor";
CREATE TABLE "AssociateProfessor" (c0 text);
DROP TABLE IF EXISTS "Astronomy";
CREATE TABLE "Astronomy" (c0 text);
DROP TABLE IF EXISTS "Science";
CREATE TABLE "Science" (c0 text);
DROP TABLE IF EXISTS "Badminton";
CREATE TABLE "Badminton" (c0 text);
DROP TABLE IF EXISTS "Sports";
CREATE TABLE "Sports" (c0 text);
DROP TABLE IF EXISTS "BasketBall";
CREATE TABLE "BasketBall" (c0 text);
DROP TABLE IF EXISTS "BasketBallFan";
CREATE TABLE "BasketBallFan" (c0 text);
DROP TABLE IF EXISTS "isCrazyAbout";
CREATE TABLE "isCrazyAbout" (c0 text, c1 text);
DROP TABLE IF EXISTS "BasketBallLover";
CREATE TABLE "BasketBallLover" (c0 text);
DROP TABLE IF EXISTS "loves";
CREATE TABLE "loves" (c0 text, c1 text);
DROP TABLE IF EXISTS "Biology";
CREATE TABLE "Biology" (c0 text);
DROP TABLE IF EXISTS "BiomedicalEngineering";
CREATE TABLE "BiomedicalEngineering" (c0 text);
DROP TABLE IF EXISTS "Book";
CREATE TABLE "Book" (c0 text);
DROP TABLE IF EXISTS "Chair";
CREATE TABLE "Chair" (c0 text);
DROP TABLE IF EXISTS "FullProfessor";
CREATE TABLE "FullProfessor" (c0 text);
DROP TABLE IF EXISTS "isHeadOf";
CREATE TABLE "isHeadOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "Department";
CREATE TABLE "Department" (c0 text);
DROP TABLE IF EXISTS "ChemicalEngineering";
CREATE TABLE "ChemicalEngineering" (c0 text);
DROP TABLE IF EXISTS "Chemistry";
CREATE TABLE "Chemistry" (c0 text);
DROP TABLE IF EXISTS "CivilEngineering";
CREATE TABLE "CivilEngineering" (c0 text);
DROP TABLE IF EXISTS "ClericalStaff";
CREATE TABLE "ClericalStaff" (c0 text);
DROP TABLE IF EXISTS "SupportingStaff";
CREATE TABLE "SupportingStaff" (c0 text);
DROP TABLE IF EXISTS "CoEdCollege";
CREATE TABLE "CoEdCollege" (c0 text);
DROP TABLE IF EXISTS "College";
CREATE TABLE "College" (c0 text);
DROP TABLE IF EXISTS "Organization";
CREATE TABLE "Organization" (c0 text);
DROP TABLE IF EXISTS "ComputerEngineering";
CREATE TABLE "ComputerEngineering" (c0 text);
DROP TABLE IF EXISTS "ComputerScience";
CREATE TABLE "ComputerScience" (c0 text);
DROP TABLE IF EXISTS "ConferencePaper";
CREATE TABLE "ConferencePaper" (c0 text);
DROP TABLE IF EXISTS "Cricket";
CREATE TABLE "Cricket" (c0 text);
DROP TABLE IF EXISTS "Dean";
CREATE TABLE "Dean" (c0 text);
DROP TABLE IF EXISTS "DesignManagement";
CREATE TABLE "DesignManagement" (c0 text);
DROP TABLE IF EXISTS "Management";
CREATE TABLE "Management" (c0 text);
DROP TABLE IF EXISTS "Director";
CREATE TABLE "Director" (c0 text);
DROP TABLE IF EXISTS "Program";
CREATE TABLE "Program" (c0 text);
DROP TABLE IF EXISTS "Drama";
CREATE TABLE "Drama" (c0 text);
DROP TABLE IF EXISTS "Economics";
CREATE TABLE "Economics" (c0 text);
DROP TABLE IF EXISTS "ElectiveCourse";
CREATE TABLE "ElectiveCourse" (c0 text);
DROP TABLE IF EXISTS "Course";
CREATE TABLE "Course" (c0 text);
DROP TABLE IF EXISTS "ElectricalEngineering";
CREATE TABLE "ElectricalEngineering" (c0 text);
DROP TABLE IF EXISTS "Employee";
CREATE TABLE "Employee" (c0 text);
DROP TABLE IF EXISTS "Person";
CREATE TABLE "Person" (c0 text);
DROP TABLE IF EXISTS "worksFor";
CREATE TABLE "worksFor" (c0 text, c1 text);
DROP TABLE IF EXISTS "EmployeeEvaluationCommittee";
CREATE TABLE "EmployeeEvaluationCommittee" (c0 text);
DROP TABLE IF EXISTS "EvaluationCommittee";
CREATE TABLE "EvaluationCommittee" (c0 text);
DROP TABLE IF EXISTS "CollegeDiscipline";
CREATE TABLE "CollegeDiscipline" (c0 text);
DROP TABLE IF EXISTS "English";
CREATE TABLE "English" (c0 text);
DROP TABLE IF EXISTS "Faculty";
CREATE TABLE "Faculty" (c0 text);
DROP TABLE IF EXISTS "teachesCourse";
CREATE TABLE "teachesCourse" (c0 text, c1 text);
DROP TABLE IF EXISTS "FinancialAndAccountingManagement";
CREATE TABLE "FinancialAndAccountingManagement" (c0 text);
DROP TABLE IF EXISTS "FootBall";
CREATE TABLE "FootBall" (c0 text);
DROP TABLE IF EXISTS "Game";
CREATE TABLE "Game" (c0 text);
DROP TABLE IF EXISTS "Interest";
CREATE TABLE "Interest" (c0 text);
DROP TABLE IF EXISTS "Geosciences";
CREATE TABLE "Geosciences" (c0 text);
DROP TABLE IF EXISTS "History";
CREATE TABLE "History" (c0 text);
DROP TABLE IF EXISTS "HumanResourceManagement";
CREATE TABLE "HumanResourceManagement" (c0 text);
DROP TABLE IF EXISTS "Humanities";
CREATE TABLE "Humanities" (c0 text);
DROP TABLE IF EXISTS "IndustryEngineering";
CREATE TABLE "IndustryEngineering" (c0 text);
DROP TABLE IF EXISTS "Institute";
CREATE TABLE "Institute" (c0 text);
DROP TABLE IF EXISTS "JournalArticle";
CREATE TABLE "JournalArticle" (c0 text);
DROP TABLE IF EXISTS "LatinArts";
CREATE TABLE "LatinArts" (c0 text);
DROP TABLE IF EXISTS "Lecturer";
CREATE TABLE "Lecturer" (c0 text);
DROP TABLE IF EXISTS "Linguistics";
CREATE TABLE "Linguistics" (c0 text);
DROP TABLE IF EXISTS "Manual";
CREATE TABLE "Manual" (c0 text);
DROP TABLE IF EXISTS "MarineScience";
CREATE TABLE "MarineScience" (c0 text);
DROP TABLE IF EXISTS "MarketingManagement";
CREATE TABLE "MarketingManagement" (c0 text);
DROP TABLE IF EXISTS "MaterialScienceEngineering";
CREATE TABLE "MaterialScienceEngineering" (c0 text);
DROP TABLE IF EXISTS "MaterialsScience";
CREATE TABLE "MaterialsScience" (c0 text);
DROP TABLE IF EXISTS "Mathematics";
CREATE TABLE "Mathematics" (c0 text);
DROP TABLE IF EXISTS "MechanicalEngineering";
CREATE TABLE "MechanicalEngineering" (c0 text);
DROP TABLE IF EXISTS "MediaArtsAndSciences";
CREATE TABLE "MediaArtsAndSciences" (c0 text);
DROP TABLE IF EXISTS "MedievalArts";
CREATE TABLE "MedievalArts" (c0 text);
DROP TABLE IF EXISTS "ModernArts";
CREATE TABLE "ModernArts" (c0 text);
DROP TABLE IF EXISTS "ModernLanguages";
CREATE TABLE "ModernLanguages" (c0 text);
DROP TABLE IF EXISTS "Movie";
CREATE TABLE "Movie" (c0 text);
DROP TABLE IF EXISTS "Music";
CREATE TABLE "Music" (c0 text);
DROP TABLE IF EXISTS "MusicsClass";
CREATE TABLE "MusicsClass" (c0 text);
DROP TABLE IF EXISTS "NonScience";
CREATE TABLE "NonScience" (c0 text);
DROP TABLE IF EXISTS "NonScienceStudent";
CREATE TABLE "NonScienceStudent" (c0 text);
DROP TABLE IF EXISTS "Student";
CREATE TABLE "Student" (c0 text);
DROP TABLE IF EXISTS "hasMajor";
CREATE TABLE "hasMajor" (c0 text, c1 text);
DROP TABLE IF EXISTS "OperationsManagement";
CREATE TABLE "OperationsManagement" (c0 text);
DROP TABLE IF EXISTS "OtherStaff";
CREATE TABLE "OtherStaff" (c0 text);
DROP TABLE IF EXISTS "PGProgram";
CREATE TABLE "PGProgram" (c0 text);
DROP TABLE IF EXISTS "PGStudent";
CREATE TABLE "PGStudent" (c0 text);
DROP TABLE IF EXISTS "enrollFor";
CREATE TABLE "enrollFor" (c0 text, c1 text);
DROP TABLE IF EXISTS "Painting";
CREATE TABLE "Painting" (c0 text);
DROP TABLE IF EXISTS "PeopleWithHobby";
CREATE TABLE "PeopleWithHobby" (c0 text);
DROP TABLE IF EXISTS "likes";
CREATE TABLE "likes" (c0 text, c1 text);
DROP TABLE IF EXISTS "PerformingArts";
CREATE TABLE "PerformingArts" (c0 text);
DROP TABLE IF EXISTS "PetroleumlEngineering";
CREATE TABLE "PetroleumlEngineering" (c0 text);
DROP TABLE IF EXISTS "PhDProgram";
CREATE TABLE "PhDProgram" (c0 text);
DROP TABLE IF EXISTS "PhDStudent";
CREATE TABLE "PhDStudent" (c0 text);
DROP TABLE IF EXISTS "Philosophy";
CREATE TABLE "Philosophy" (c0 text);
DROP TABLE IF EXISTS "Physics";
CREATE TABLE "Physics" (c0 text);
DROP TABLE IF EXISTS "PostDoc";
CREATE TABLE "PostDoc" (c0 text);
DROP TABLE IF EXISTS "ProjectManagement";
CREATE TABLE "ProjectManagement" (c0 text);
DROP TABLE IF EXISTS "Psychology";
CREATE TABLE "Psychology" (c0 text);
DROP TABLE IF EXISTS "PublicRelationsManagement";
CREATE TABLE "PublicRelationsManagement" (c0 text);
DROP TABLE IF EXISTS "Reading";
CREATE TABLE "Reading" (c0 text);
DROP TABLE IF EXISTS "Religions";
CREATE TABLE "Religions" (c0 text);
DROP TABLE IF EXISTS "ResearchAssistant";
CREATE TABLE "ResearchAssistant" (c0 text);
DROP TABLE IF EXISTS "ResearchGroup";
CREATE TABLE "ResearchGroup" (c0 text);
DROP TABLE IF EXISTS "ResearchProject";
CREATE TABLE "ResearchProject" (c0 text);
DROP TABLE IF EXISTS "Work";
CREATE TABLE "Work" (c0 text);
DROP TABLE IF EXISTS "RiskManagement";
CREATE TABLE "RiskManagement" (c0 text);
DROP TABLE IF EXISTS "SalesManagement";
CREATE TABLE "SalesManagement" (c0 text);
DROP TABLE IF EXISTS "School";
CREATE TABLE "School" (c0 text);
DROP TABLE IF EXISTS "ScienceStudent";
CREATE TABLE "ScienceStudent" (c0 text);
DROP TABLE IF EXISTS "Software";
CREATE TABLE "Software" (c0 text);
DROP TABLE IF EXISTS "Specification";
CREATE TABLE "Specification" (c0 text);
DROP TABLE IF EXISTS "SportsFan";
CREATE TABLE "SportsFan" (c0 text);
DROP TABLE IF EXISTS "SportsLover";
CREATE TABLE "SportsLover" (c0 text);
DROP TABLE IF EXISTS "Statistics";
CREATE TABLE "Statistics" (c0 text);
DROP TABLE IF EXISTS "enrollIn";
CREATE TABLE "enrollIn" (c0 text, c1 text);
DROP TABLE IF EXISTS "StudentEvaluationCommittee";
CREATE TABLE "StudentEvaluationCommittee" (c0 text);
DROP TABLE IF EXISTS "SupplyChainManagement";
CREATE TABLE "SupplyChainManagement" (c0 text);
DROP TABLE IF EXISTS "Swimming";
CREATE TABLE "Swimming" (c0 text);
DROP TABLE IF EXISTS "SystemStaff";
CREATE TABLE "SystemStaff" (c0 text);
DROP TABLE IF EXISTS "TeachingAssistant";
CREATE TABLE "TeachingAssistant" (c0 text);
DROP TABLE IF EXISTS "isTeachingAssistantOf";
CREATE TABLE "isTeachingAssistantOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "TeachingCourse";
CREATE TABLE "TeachingCourse" (c0 text);
DROP TABLE IF EXISTS "TechnicalReport";
CREATE TABLE "TechnicalReport" (c0 text);
DROP TABLE IF EXISTS "Tennis";
CREATE TABLE "Tennis" (c0 text);
DROP TABLE IF EXISTS "TheatreAndDance";
CREATE TABLE "TheatreAndDance" (c0 text);
DROP TABLE IF EXISTS "ThesisEvaluationCommittee";
CREATE TABLE "ThesisEvaluationCommittee" (c0 text);
DROP TABLE IF EXISTS "Travelling";
CREATE TABLE "Travelling" (c0 text);
DROP TABLE IF EXISTS "UGCourse";
CREATE TABLE "UGCourse" (c0 text);
DROP TABLE IF EXISTS "UGProgram";
CREATE TABLE "UGProgram" (c0 text);
DROP TABLE IF EXISTS "UGStudent";
CREATE TABLE "UGStudent" (c0 text);
DROP TABLE IF EXISTS "University";
CREATE TABLE "University" (c0 text);
DROP TABLE IF EXISTS "UnofficialPublication";
CREATE TABLE "UnofficialPublication" (c0 text);
DROP TABLE IF EXISTS "VisitingProfessor";
CREATE TABLE "VisitingProfessor" (c0 text);
DROP TABLE IF EXISTS "WomanCollege";
CREATE TABLE "WomanCollege" (c0 text);
DROP TABLE IF EXISTS "dislikes";
CREATE TABLE "dislikes" (c0 text, c1 text);
DROP TABLE IF EXISTS "isStudentOf";
CREATE TABLE "isStudentOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "evaluatedBy";
CREATE TABLE "evaluatedBy" (c0 text, c1 text);
DROP TABLE IF EXISTS "evaluates";
CREATE TABLE "evaluates" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasAlumnus";
CREATE TABLE "hasAlumnus" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasDegreeFrom";
CREATE TABLE "hasDegreeFrom" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasAssistantProfessor";
CREATE TABLE "hasAssistantProfessor" (c0 text, c1 text);
DROP TABLE IF EXISTS "isAssistantProfessorOf";
CREATE TABLE "isAssistantProfessorOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasProfessor";
CREATE TABLE "hasProfessor" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasAssociateProfessor";
CREATE TABLE "hasAssociateProfessor" (c0 text, c1 text);
DROP TABLE IF EXISTS "isAssociateProfessorOf";
CREATE TABLE "isAssociateProfessorOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasAuthor";
CREATE TABLE "hasAuthor" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasClericalStaff";
CREATE TABLE "hasClericalStaff" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasSupportingStaff";
CREATE TABLE "hasSupportingStaff" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasCollaborationWith";
CREATE TABLE "hasCollaborationWith" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasCollege";
CREATE TABLE "hasCollege" (c0 text, c1 text);
DROP TABLE IF EXISTS "isCollegeOf";
CREATE TABLE "isCollegeOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasSubOrganization";
CREATE TABLE "hasSubOrganization" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasCollegeDiscipline";
CREATE TABLE "hasCollegeDiscipline" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasCommitteeMembers";
CREATE TABLE "hasCommitteeMembers" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasMember";
CREATE TABLE "hasMember" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasDean";
CREATE TABLE "hasDean" (c0 text, c1 text);
DROP TABLE IF EXISTS "isDeanOf";
CREATE TABLE "isDeanOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasDepartment";
CREATE TABLE "hasDepartment" (c0 text, c1 text);
DROP TABLE IF EXISTS "isDepartmentOf";
CREATE TABLE "isDepartmentOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasDoctoralDegreeFrom";
CREATE TABLE "hasDoctoralDegreeFrom" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasEmployee";
CREATE TABLE "hasEmployee" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasEmployeeEvaluationCommittee";
CREATE TABLE "hasEmployeeEvaluationCommittee" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasEvaluationCommittee";
CREATE TABLE "hasEvaluationCommittee" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasFaculty";
CREATE TABLE "hasFaculty" (c0 text, c1 text);
DROP TABLE IF EXISTS "isFacultyOf";
CREATE TABLE "isFacultyOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasFullProfessor";
CREATE TABLE "hasFullProfessor" (c0 text, c1 text);
DROP TABLE IF EXISTS "isFullProfessorOf";
CREATE TABLE "isFullProfessorOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasHead";
CREATE TABLE "hasHead" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasLecturer";
CREATE TABLE "hasLecturer" (c0 text, c1 text);
DROP TABLE IF EXISTS "isLecturerOf";
CREATE TABLE "isLecturerOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasMasterDegreeFrom";
CREATE TABLE "hasMasterDegreeFrom" (c0 text, c1 text);
DROP TABLE IF EXISTS "isMemberOf";
CREATE TABLE "isMemberOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasOtherStaff";
CREATE TABLE "hasOtherStaff" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasPGProgram";
CREATE TABLE "hasPGProgram" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasProgram";
CREATE TABLE "hasProgram" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasPart";
CREATE TABLE "hasPart" (c0 text, c1 text);
DROP TABLE IF EXISTS "isPartOf";
CREATE TABLE "isPartOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasPhDProgram";
CREATE TABLE "hasPhDProgram" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasPostDoc";
CREATE TABLE "hasPostDoc" (c0 text, c1 text);
DROP TABLE IF EXISTS "isPostDocOf";
CREATE TABLE "isPostDocOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "isProfessorOf";
CREATE TABLE "isProfessorOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasResearchAssistant";
CREATE TABLE "hasResearchAssistant" (c0 text, c1 text);
DROP TABLE IF EXISTS "isResearchAssistantOf";
CREATE TABLE "isResearchAssistantOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasResearchGroup";
CREATE TABLE "hasResearchGroup" (c0 text, c1 text);
DROP TABLE IF EXISTS "isResearchGroupOf";
CREATE TABLE "isResearchGroupOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasResearchProject";
CREATE TABLE "hasResearchProject" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasWork";
CREATE TABLE "hasWork" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasStudent";
CREATE TABLE "hasStudent" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasStudentEvaluationCommittee";
CREATE TABLE "hasStudentEvaluationCommittee" (c0 text, c1 text);
DROP TABLE IF EXISTS "isSubOrganizationOf";
CREATE TABLE "isSubOrganizationOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasSystemStaff";
CREATE TABLE "hasSystemStaff" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasThesisEvaluationCommittee";
CREATE TABLE "hasThesisEvaluationCommittee" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasUGProgram";
CREATE TABLE "hasUGProgram" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasUndergraduateDegreeFrom";
CREATE TABLE "hasUndergraduateDegreeFrom" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasVisitingProfessor";
CREATE TABLE "hasVisitingProfessor" (c0 text, c1 text);
DROP TABLE IF EXISTS "isVisitingProfessorOf";
CREATE TABLE "isVisitingProfessorOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasWomenCollege";
CREATE TABLE "hasWomenCollege" (c0 text, c1 text);
DROP TABLE IF EXISTS "isAdvisedBy";
CREATE TABLE "isAdvisedBy" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasAdvisor";
CREATE TABLE "hasAdvisor" (c0 text, c1 text);
DROP TABLE IF EXISTS "isAffiliatedOrganizationOf";
CREATE TABLE "isAffiliatedOrganizationOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "isClericalStaffOf";
CREATE TABLE "isClericalStaffOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "isSupportingStaffOf";
CREATE TABLE "isSupportingStaffOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "isOtherStaffOf";
CREATE TABLE "isOtherStaffOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "isSystemStaffOf";
CREATE TABLE "isSystemStaffOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "isTaughtBy";
CREATE TABLE "isTaughtBy" (c0 text, c1 text);
DROP TABLE IF EXISTS "isWomenCollegeOf";
CREATE TABLE "isWomenCollegeOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "offerCourse";
CREATE TABLE "offerCourse" (c0 text, c1 text);
DROP TABLE IF EXISTS "orgPublication";
CREATE TABLE "orgPublication" (c0 text, c1 text);
DROP TABLE IF EXISTS "publicationResearch";
CREATE TABLE "publicationResearch" (c0 text, c1 text);
DROP TABLE IF EXISTS "takesCourse";
CREATE TABLE "takesCourse" (c0 text, c1 text);
DROP TABLE IF EXISTS "tenured";
CREATE TABLE "tenured" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasAge";
CREATE TABLE "hasAge" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasEmailAddress";
CREATE TABLE "hasEmailAddress" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasFirstName";
CREATE TABLE "hasFirstName" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasLastName";
CREATE TABLE "hasLastName" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasTelephone";
CREATE TABLE "hasTelephone" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasTitle";
CREATE TABLE "hasTitle" (c0 text, c1 text);