DROP TABLE IF EXISTS "AdministrativeStaff";
CREATE TABLE "AdministrativeStaff" (c0 text);
INSERT INTO "AdministrativeStaff" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Employee";
CREATE TABLE "Employee" (c0 text);
INSERT INTO "Employee" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "AssistantProfessor";
CREATE TABLE "AssistantProfessor" (c0 text);
INSERT INTO "AssistantProfessor" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Professor";
CREATE TABLE "Professor" (c0 text);
INSERT INTO "Professor" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "AssociateProfessor";
CREATE TABLE "AssociateProfessor" (c0 text);
INSERT INTO "AssociateProfessor" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "BachelorExam";
CREATE TABLE "BachelorExam" (c0 text);
INSERT INTO "BachelorExam" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Exam";
CREATE TABLE "Exam" (c0 text);
INSERT INTO "Exam" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Career";
CREATE TABLE "Career" (c0 text);
INSERT INTO "Career" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Work";
CREATE TABLE "Work" (c0 text);
INSERT INTO "Work" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Chair";
CREATE TABLE "Chair" (c0 text);
INSERT INTO "Chair" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "ClericalStaff";
CREATE TABLE "ClericalStaff" (c0 text);
INSERT INTO "ClericalStaff" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "College";
CREATE TABLE "College" (c0 text);
INSERT INTO "College" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Organization";
CREATE TABLE "Organization" (c0 text);
INSERT INTO "Organization" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Course";
CREATE TABLE "Course" (c0 text);
INSERT INTO "Course" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Dean";
CREATE TABLE "Dean" (c0 text);
INSERT INTO "Dean" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "headOf";
CREATE TABLE "headOf" (c0 text, c1 text);
INSERT INTO "headOf" SELECT MD5(random()::text), MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Degree";
CREATE TABLE "Degree" (c0 text);
INSERT INTO "Degree" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Director";
CREATE TABLE "Director" (c0 text);
INSERT INTO "Director" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Person";
CREATE TABLE "Person" (c0 text);
INSERT INTO "Person" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Program";
CREATE TABLE "Program" (c0 text);
INSERT INTO "Program" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "worksFor";
CREATE TABLE "worksFor" (c0 text, c1 text);
INSERT INTO "worksFor" SELECT MD5(random()::text), MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "ExDean";
CREATE TABLE "ExDean" (c0 text);
INSERT INTO "ExDean" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "ExamRecord";
CREATE TABLE "ExamRecord" (c0 text);
INSERT INTO "ExamRecord" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Faculty";
CREATE TABLE "Faculty" (c0 text);
INSERT INTO "Faculty" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "FacultyStaff";
CREATE TABLE "FacultyStaff" (c0 text);
INSERT INTO "FacultyStaff" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "FullProfessor";
CREATE TABLE "FullProfessor" (c0 text);
INSERT INTO "FullProfessor" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "GraduateCourse";
CREATE TABLE "GraduateCourse" (c0 text);
INSERT INTO "GraduateCourse" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "GraduateStudent";
CREATE TABLE "GraduateStudent" (c0 text);
INSERT INTO "GraduateStudent" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "takesCourse";
CREATE TABLE "takesCourse" (c0 text, c1 text);
INSERT INTO "takesCourse" SELECT MD5(random()::text), MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Lecturer";
CREATE TABLE "Lecturer" (c0 text);
INSERT INTO "Lecturer" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "PostDoc";
CREATE TABLE "PostDoc" (c0 text);
INSERT INTO "PostDoc" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "ResearchAssistant";
CREATE TABLE "ResearchAssistant" (c0 text);
INSERT INTO "ResearchAssistant" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "Student";
CREATE TABLE "Student" (c0 text);
INSERT INTO "Student" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "SystemsStaff";
CREATE TABLE "SystemsStaff" (c0 text);
INSERT INTO "SystemsStaff" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "UndergraduateStudent";
CREATE TABLE "UndergraduateStudent" (c0 text);
INSERT INTO "UndergraduateStudent" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "University";
CREATE TABLE "University" (c0 text);
INSERT INTO "University" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "VisitingProfessor";
CREATE TABLE "VisitingProfessor" (c0 text);
INSERT INTO "VisitingProfessor" SELECT MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "advisor";
CREATE TABLE "advisor" (c0 text, c1 text);
INSERT INTO "advisor" SELECT MD5(random()::text), MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "affiliateOf";
CREATE TABLE "affiliateOf" (c0 text, c1 text);
INSERT INTO "affiliateOf" SELECT MD5(random()::text), MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "affiliatedOrganizationOf";
CREATE TABLE "affiliatedOrganizationOf" (c0 text, c1 text);
INSERT INTO "affiliatedOrganizationOf" SELECT MD5(random()::text), MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "degreeFrom";
CREATE TABLE "degreeFrom" (c0 text, c1 text);
INSERT INTO "degreeFrom" SELECT MD5(random()::text), MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "hasAlumnus";
CREATE TABLE "hasAlumnus" (c0 text, c1 text);
INSERT INTO "hasAlumnus" SELECT MD5(random()::text), MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "doctoralDegreeFrom";
CREATE TABLE "doctoralDegreeFrom" (c0 text, c1 text);
INSERT INTO "doctoralDegreeFrom" SELECT MD5(random()::text), MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "hasExamRecord";
CREATE TABLE "hasExamRecord" (c0 text, c1 text);
INSERT INTO "hasExamRecord" SELECT MD5(random()::text), MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "hasFaculty";
CREATE TABLE "hasFaculty" (c0 text, c1 text);
INSERT INTO "hasFaculty" SELECT MD5(random()::text), MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "isPartOfUniversity";
CREATE TABLE "isPartOfUniversity" (c0 text, c1 text);
INSERT INTO "isPartOfUniversity" SELECT MD5(random()::text), MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "mastersDegreeFrom";
CREATE TABLE "mastersDegreeFrom" (c0 text, c1 text);
INSERT INTO "mastersDegreeFrom" SELECT MD5(random()::text), MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "member";
CREATE TABLE "member" (c0 text, c1 text);
INSERT INTO "member" SELECT MD5(random()::text), MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "memberOf";
CREATE TABLE "memberOf" (c0 text, c1 text);
INSERT INTO "memberOf" SELECT MD5(random()::text), MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "orgPublication";
CREATE TABLE "orgPublication" (c0 text, c1 text);
INSERT INTO "orgPublication" SELECT MD5(random()::text), MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "publicationAuthor";
CREATE TABLE "publicationAuthor" (c0 text, c1 text);
INSERT INTO "publicationAuthor" SELECT MD5(random()::text), MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "teacherOf";
CREATE TABLE "teacherOf" (c0 text, c1 text);
INSERT INTO "teacherOf" SELECT MD5(random()::text), MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "teachingAssistantOf";
CREATE TABLE "teachingAssistantOf" (c0 text, c1 text);
INSERT INTO "teachingAssistantOf" SELECT MD5(random()::text), MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "tenured";
CREATE TABLE "tenured" (c0 text, c1 text);
INSERT INTO "tenured" SELECT MD5(random()::text), MD5(random()::text) FROM generate_series(1, 10);
DROP TABLE IF EXISTS "undergraduateDegreeFrom";
CREATE TABLE "undergraduateDegreeFrom" (c0 text, c1 text);
INSERT INTO "undergraduateDegreeFrom" SELECT MD5(random()::text), MD5(random()::text) FROM generate_series(1, 10);