PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX : <http://www.owl-ontologies.com/Ontology1207768242.owl#>
SELECT DISTINCT ?0 ?1 
WHERE
{
	?0  rdf:type :Person .
	?0  :hasStock ?1  .
	?1  rdf:type :Stock
}
