PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX : <http://www.owl-ontologies.com/Ontology1207768242.owl#>
SELECT DISTINCT ?0 ?1 ?2 ?3 
WHERE
{
	?0  rdf:type :FinantialInstrument .
	?0  :belongsToCompany ?1  .
	?1  rdf:type :Company .
	?1  :hasStock ?2  .
	?2  rdf:type :Stock .
	?1  :isListedIn ?3  .
	?3  rdf:type :StockExchangeList
}
