#!/bin/bash

#JAVA=~/.sdkman/candidates/java/8.0.201-oracle/jre/bin/java
JAVA=java
ONTOP_JAVA_ARGS="-Xmx4096m"
# <http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in>

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done

ONTOP_HOME="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

if [ -z "${ONTOP_JAVA_ARGS}" ]; then
  ONTOP_JAVA_ARGS="-Xmx4096m"
fi
${JAVA} -Xmx6g -cp "${ONTOP_HOME}/lib/*:${ONTOP_HOME}/jdbc/*" -Dlogback.configurationFile="${ONTOP_HOME}/log/logback.xml" \
 it.unibz.inf.ontop.cli.Ontop $@
