DROP TABLE IF EXISTS "Acquisition";
CREATE TABLE "Acquisition" (c0 text);
DROP TABLE IF EXISTS "Transaction";
CREATE TABLE "Transaction" (c0 text);
DROP TABLE IF EXISTS "Address";
CREATE TABLE "Address" (c0 text);
DROP TABLE IF EXISTS "Thing";
CREATE TABLE "Thing" (c0 text);
DROP TABLE IF EXISTS "inverseofhasAddress";
CREATE TABLE "inverseofhasAddress" (c0 text, c1 text);
DROP TABLE IF EXISTS "Company";
CREATE TABLE "Company" (c0 text);
DROP TABLE IF EXISTS "LegalPerson";
CREATE TABLE "LegalPerson" (c0 text);
DROP TABLE IF EXISTS "Dealer";
CREATE TABLE "Dealer" (c0 text);
DROP TABLE IF EXISTS "StockBroker";
CREATE TABLE "StockBroker" (c0 text);
DROP TABLE IF EXISTS "Investor";
CREATE TABLE "Investor" (c0 text);
DROP TABLE IF EXISTS "Person";
CREATE TABLE "Person" (c0 text);
DROP TABLE IF EXISTS "Offer";
CREATE TABLE "Offer" (c0 text);
DROP TABLE IF EXISTS "hasAddress";
CREATE TABLE "hasAddress" (c0 text, c1 text);
DROP TABLE IF EXISTS "PhysicalPerson";
CREATE TABLE "PhysicalPerson" (c0 text);
DROP TABLE IF EXISTS "Stock";
CREATE TABLE "Stock" (c0 text);
DROP TABLE IF EXISTS "FinantialInstrument";
CREATE TABLE "FinantialInstrument" (c0 text);
DROP TABLE IF EXISTS "isListedIn";
CREATE TABLE "isListedIn" (c0 text, c1 text);
DROP TABLE IF EXISTS "belongsToCompany";
CREATE TABLE "belongsToCompany" (c0 text, c1 text);
DROP TABLE IF EXISTS "StockExchangeMember";
CREATE TABLE "StockExchangeMember" (c0 text);
DROP TABLE IF EXISTS "tradesOnBehalfOf";
CREATE TABLE "tradesOnBehalfOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "StockTrader";
CREATE TABLE "StockTrader" (c0 text);
DROP TABLE IF EXISTS "Trader";
CREATE TABLE "Trader" (c0 text);
DROP TABLE IF EXISTS "isExecutedFor";
CREATE TABLE "isExecutedFor" (c0 text, c1 text);
DROP TABLE IF EXISTS "isExecutedBy";
CREATE TABLE "isExecutedBy" (c0 text, c1 text);
DROP TABLE IF EXISTS "involvesInstrument";
CREATE TABLE "involvesInstrument" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasStock";
CREATE TABLE "hasStock" (c0 text, c1 text);
DROP TABLE IF EXISTS "StockExchangeList";
CREATE TABLE "StockExchangeList" (c0 text);
DROP TABLE IF EXISTS "listsStock";
CREATE TABLE "listsStock" (c0 text, c1 text);
DROP TABLE IF EXISTS "isTradedIn";
CREATE TABLE "isTradedIn" (c0 text, c1 text);
DROP TABLE IF EXISTS "usesBroker";
CREATE TABLE "usesBroker" (c0 text, c1 text);