DROP TABLE IF EXISTS "AdministrativeStaff";
CREATE TABLE "AdministrativeStaff" (c0 text);
DROP TABLE IF EXISTS "Employee";
CREATE TABLE "Employee" (c0 text);
DROP TABLE IF EXISTS "AssistantProfessor";
CREATE TABLE "AssistantProfessor" (c0 text);
DROP TABLE IF EXISTS "Professor";
CREATE TABLE "Professor" (c0 text);
DROP TABLE IF EXISTS "AssociateProfessor";
CREATE TABLE "AssociateProfessor" (c0 text);
DROP TABLE IF EXISTS "BachelorExam";
CREATE TABLE "BachelorExam" (c0 text);
DROP TABLE IF EXISTS "Exam";
CREATE TABLE "Exam" (c0 text);
DROP TABLE IF EXISTS "Career";
CREATE TABLE "Career" (c0 text);
DROP TABLE IF EXISTS "Work";
CREATE TABLE "Work" (c0 text);
DROP TABLE IF EXISTS "Chair";
CREATE TABLE "Chair" (c0 text);
DROP TABLE IF EXISTS "ClericalStaff";
CREATE TABLE "ClericalStaff" (c0 text);
DROP TABLE IF EXISTS "College";
CREATE TABLE "College" (c0 text);
DROP TABLE IF EXISTS "Organization";
CREATE TABLE "Organization" (c0 text);
DROP TABLE IF EXISTS "Course";
CREATE TABLE "Course" (c0 text);
DROP TABLE IF EXISTS "Dean";
CREATE TABLE "Dean" (c0 text);
DROP TABLE IF EXISTS "headOf";
CREATE TABLE "headOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "Degree";
CREATE TABLE "Degree" (c0 text);
DROP TABLE IF EXISTS "Director";
CREATE TABLE "Director" (c0 text);
DROP TABLE IF EXISTS "Person";
CREATE TABLE "Person" (c0 text);
DROP TABLE IF EXISTS "Program";
CREATE TABLE "Program" (c0 text);
DROP TABLE IF EXISTS "worksFor";
CREATE TABLE "worksFor" (c0 text, c1 text);
DROP TABLE IF EXISTS "ExDean";
CREATE TABLE "ExDean" (c0 text);
DROP TABLE IF EXISTS "ExamRecord";
CREATE TABLE "ExamRecord" (c0 text);
DROP TABLE IF EXISTS "Faculty";
CREATE TABLE "Faculty" (c0 text);
DROP TABLE IF EXISTS "FacultyStaff";
CREATE TABLE "FacultyStaff" (c0 text);
DROP TABLE IF EXISTS "FullProfessor";
CREATE TABLE "FullProfessor" (c0 text);
DROP TABLE IF EXISTS "GraduateCourse";
CREATE TABLE "GraduateCourse" (c0 text);
DROP TABLE IF EXISTS "GraduateStudent";
CREATE TABLE "GraduateStudent" (c0 text);
DROP TABLE IF EXISTS "takesCourse";
CREATE TABLE "takesCourse" (c0 text, c1 text);
DROP TABLE IF EXISTS "Lecturer";
CREATE TABLE "Lecturer" (c0 text);
DROP TABLE IF EXISTS "PostDoc";
CREATE TABLE "PostDoc" (c0 text);
DROP TABLE IF EXISTS "ResearchAssistant";
CREATE TABLE "ResearchAssistant" (c0 text);
DROP TABLE IF EXISTS "Student";
CREATE TABLE "Student" (c0 text);
DROP TABLE IF EXISTS "SystemsStaff";
CREATE TABLE "SystemsStaff" (c0 text);
DROP TABLE IF EXISTS "UndergraduateStudent";
CREATE TABLE "UndergraduateStudent" (c0 text);
DROP TABLE IF EXISTS "University";
CREATE TABLE "University" (c0 text);
DROP TABLE IF EXISTS "VisitingProfessor";
CREATE TABLE "VisitingProfessor" (c0 text);
DROP TABLE IF EXISTS "advisor";
CREATE TABLE "advisor" (c0 text, c1 text);
DROP TABLE IF EXISTS "affiliateOf";
CREATE TABLE "affiliateOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "affiliatedOrganizationOf";
CREATE TABLE "affiliatedOrganizationOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "degreeFrom";
CREATE TABLE "degreeFrom" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasAlumnus";
CREATE TABLE "hasAlumnus" (c0 text, c1 text);
DROP TABLE IF EXISTS "doctoralDegreeFrom";
CREATE TABLE "doctoralDegreeFrom" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasExamRecord";
CREATE TABLE "hasExamRecord" (c0 text, c1 text);
DROP TABLE IF EXISTS "hasFaculty";
CREATE TABLE "hasFaculty" (c0 text, c1 text);
DROP TABLE IF EXISTS "isPartOfUniversity";
CREATE TABLE "isPartOfUniversity" (c0 text, c1 text);
DROP TABLE IF EXISTS "mastersDegreeFrom";
CREATE TABLE "mastersDegreeFrom" (c0 text, c1 text);
DROP TABLE IF EXISTS "member";
CREATE TABLE "member" (c0 text, c1 text);
DROP TABLE IF EXISTS "memberOf";
CREATE TABLE "memberOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "orgPublication";
CREATE TABLE "orgPublication" (c0 text, c1 text);
DROP TABLE IF EXISTS "publicationAuthor";
CREATE TABLE "publicationAuthor" (c0 text, c1 text);
DROP TABLE IF EXISTS "teacherOf";
CREATE TABLE "teacherOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "teachingAssistantOf";
CREATE TABLE "teachingAssistantOf" (c0 text, c1 text);
DROP TABLE IF EXISTS "tenured";
CREATE TABLE "tenured" (c0 text, c1 text);
DROP TABLE IF EXISTS "undergraduateDegreeFrom";
CREATE TABLE "undergraduateDegreeFrom" (c0 text, c1 text);