FROM node:10-alpine

RUN mkdir -p /usr/src/
RUN mkdir -p /usr/logs/
WORKDIR /usr/src/

COPY package.json /usr/src/
COPY yarn.lock /usr/src/

COPY . /usr/src/

RUN yarn

CMD ["node", "app/dockerload.js"]
