FROM node:10-alpine

RUN mkdir -p /framework
WORKDIR /framework

COPY package.json /framework/
COPY yarn.lock /framework/
RUN yarn

COPY . /framework
COPY ./scenarios /framework/

CMD ["node", "./app/dockerload.js"]
