DROP TABLE IF EXISTS "src_Chemistry";
CREATE TABLE "src_Chemistry" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Biology";
CREATE TABLE "src_Biology" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Physics";
CREATE TABLE "src_Physics" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_School";
CREATE TABLE "src_School" (c0 text , c1 text , c2 text , c3 text);
DROP TABLE IF EXISTS "src_PhDProgram";
CREATE TABLE "src_PhDProgram" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Institute";
CREATE TABLE "src_Institute" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_MechanicalEngineering";
CREATE TABLE "src_MechanicalEngineering" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_FinancialAndAccountingManagement";
CREATE TABLE "src_FinancialAndAccountingManagement" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Engineering";
CREATE TABLE "src_Engineering" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_MediaArtsAndSciences";
CREATE TABLE "src_MediaArtsAndSciences" (c0 text);
DROP TABLE IF EXISTS "src_PGStudent";
CREATE TABLE "src_PGStudent" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_SportsLover";
CREATE TABLE "src_SportsLover" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_hasUndergraduateDegreeFrom";
CREATE TABLE "src_hasUndergraduateDegreeFrom" (c0 text , c1 text , c2 text , c3 text);
DROP TABLE IF EXISTS "src_isProfessorOf";
CREATE TABLE "src_isProfessorOf" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_ChemicalEngineering";
CREATE TABLE "src_ChemicalEngineering" (c0 text);
DROP TABLE IF EXISTS "src_VisitingProfessor";
CREATE TABLE "src_VisitingProfessor" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_isSystemStaffOf";
CREATE TABLE "src_isSystemStaffOf" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_hasClericalStaff";
CREATE TABLE "src_hasClericalStaff" (c0 text , c1 text , c2 text , c3 text);
DROP TABLE IF EXISTS "src_Swimming";
CREATE TABLE "src_Swimming" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Drama";
CREATE TABLE "src_Drama" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Linguistics";
CREATE TABLE "src_Linguistics" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_TheatreAndDance";
CREATE TABLE "src_TheatreAndDance" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Program";
CREATE TABLE "src_Program" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_MaterialsScience";
CREATE TABLE "src_MaterialsScience" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Specification";
CREATE TABLE "src_Specification" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_hasStudentEvaluationCommittee";
CREATE TABLE "src_hasStudentEvaluationCommittee" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_hasFaculty";
CREATE TABLE "src_hasFaculty" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_DesignManagement";
CREATE TABLE "src_DesignManagement" (c0 text);
DROP TABLE IF EXISTS "src_HumanResourceManagement";
CREATE TABLE "src_HumanResourceManagement" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_hasAdvisor";
CREATE TABLE "src_hasAdvisor" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_isAffiliatedOrganizationOf";
CREATE TABLE "src_isAffiliatedOrganizationOf" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Department";
CREATE TABLE "src_Department" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_hasEmailAddress";
CREATE TABLE "src_hasEmailAddress" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_orgPublication";
CREATE TABLE "src_orgPublication" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_hasSupportingStaff";
CREATE TABLE "src_hasSupportingStaff" (c0 text , c1 text , c2 text , c3 text);
DROP TABLE IF EXISTS "src_isTaughtBy";
CREATE TABLE "src_isTaughtBy" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_isHeadOf";
CREATE TABLE "src_isHeadOf" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_University";
CREATE TABLE "src_University" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_FullProfessor";
CREATE TABLE "src_FullProfessor" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_isDeanOf";
CREATE TABLE "src_isDeanOf" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_EvaluationCommittee";
CREATE TABLE "src_EvaluationCommittee" (c0 text);
DROP TABLE IF EXISTS "src_ModernLanguages";
CREATE TABLE "src_ModernLanguages" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_UnofficialPublication";
CREATE TABLE "src_UnofficialPublication" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_College";
CREATE TABLE "src_College" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Psychology";
CREATE TABLE "src_Psychology" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_hasDepartment";
CREATE TABLE "src_hasDepartment" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Travelling";
CREATE TABLE "src_Travelling" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_FootBall";
CREATE TABLE "src_FootBall" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_enrollIn";
CREATE TABLE "src_enrollIn" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_UGProgram";
CREATE TABLE "src_UGProgram" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Economics";
CREATE TABLE "src_Economics" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_ResearchGroup";
CREATE TABLE "src_ResearchGroup" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_hasAssistantProfessor";
CREATE TABLE "src_hasAssistantProfessor" (c0 text , c1 text , c2 text , c3 text);
DROP TABLE IF EXISTS "src_Movie";
CREATE TABLE "src_Movie" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Faculty";
CREATE TABLE "src_Faculty" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Book";
CREATE TABLE "src_Book" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Philosophy";
CREATE TABLE "src_Philosophy" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_hasCommitteeMembers";
CREATE TABLE "src_hasCommitteeMembers" (c0 text , c1 text , c2 text , c3 text);
DROP TABLE IF EXISTS "src_hasEmployeeEvaluationCommittee";
CREATE TABLE "src_hasEmployeeEvaluationCommittee" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_MedievalArts";
CREATE TABLE "src_MedievalArts" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_hasSystemStaff";
CREATE TABLE "src_hasSystemStaff" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Organization";
CREATE TABLE "src_Organization" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Chair";
CREATE TABLE "src_Chair" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_hasResearchGroup";
CREATE TABLE "src_hasResearchGroup" (c0 text , c1 text , c2 text , c3 text);
DROP TABLE IF EXISTS "src_isPostDocOf";
CREATE TABLE "src_isPostDocOf" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Management";
CREATE TABLE "src_Management" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_isWomenCollegeOf";
CREATE TABLE "src_isWomenCollegeOf" (c0 text , c1 text , c2 text , c3 text);
DROP TABLE IF EXISTS "src_hasFirstName";
CREATE TABLE "src_hasFirstName" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_hasTelephone";
CREATE TABLE "src_hasTelephone" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Architecture";
CREATE TABLE "src_Architecture" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_PeopleWithHobby";
CREATE TABLE "src_PeopleWithHobby" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_hasVisitingProfessor";
CREATE TABLE "src_hasVisitingProfessor" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_ResearchProject";
CREATE TABLE "src_ResearchProject" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_hasPGProgram";
CREATE TABLE "src_hasPGProgram" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_hasWomenCollege";
CREATE TABLE "src_hasWomenCollege" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_PostDoc";
CREATE TABLE "src_PostDoc" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Sports";
CREATE TABLE "src_Sports" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_MusicsClass";
CREATE TABLE "src_MusicsClass" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_FineArts";
CREATE TABLE "src_FineArts" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_BasketBallLover";
CREATE TABLE "src_BasketBallLover" (c0 text);
DROP TABLE IF EXISTS "src_Mathematics";
CREATE TABLE "src_Mathematics" (c0 text);
DROP TABLE IF EXISTS "src_PGProgram";
CREATE TABLE "src_PGProgram" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_hasDoctoralDegreeFrom";
CREATE TABLE "src_hasDoctoralDegreeFrom" (c0 text , c1 text , c2 text , c3 text);
DROP TABLE IF EXISTS "src_publicationResearch";
CREATE TABLE "src_publicationResearch" (c0 text , c1 text , c2 text , c3 text);
DROP TABLE IF EXISTS "src_hasPhDProgram";
CREATE TABLE "src_hasPhDProgram" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Badminton";
CREATE TABLE "src_Badminton" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_HumanitiesAndSocial";
CREATE TABLE "src_HumanitiesAndSocial" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_TeachingAssistant";
CREATE TABLE "src_TeachingAssistant" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Statistics";
CREATE TABLE "src_Statistics" (c0 text);
DROP TABLE IF EXISTS "src_evaluates";
CREATE TABLE "src_evaluates" (c0 text , c1 text , c2 text , c3 text);
DROP TABLE IF EXISTS "src_ClericalStaff";
CREATE TABLE "src_ClericalStaff" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_isResearchGroupOf";
CREATE TABLE "src_isResearchGroupOf" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_MarketingManagement";
CREATE TABLE "src_MarketingManagement" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_ScienceStudent";
CREATE TABLE "src_ScienceStudent" (c0 text);
DROP TABLE IF EXISTS "src_SalesManagement";
CREATE TABLE "src_SalesManagement" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_hasUGProgram";
CREATE TABLE "src_hasUGProgram" (c0 text , c1 text , c2 text , c3 text);
DROP TABLE IF EXISTS "src_enrollFor";
CREATE TABLE "src_enrollFor" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_hasCollaborationWith";
CREATE TABLE "src_hasCollaborationWith" (c0 text , c1 text , c2 text , c3 text);
DROP TABLE IF EXISTS "src_SystemStaff";
CREATE TABLE "src_SystemStaff" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_dislikes";
CREATE TABLE "src_dislikes" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_ProjectManagement";
CREATE TABLE "src_ProjectManagement" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_TechnicalReport";
CREATE TABLE "src_TechnicalReport" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_SupportingStaff";
CREATE TABLE "src_SupportingStaff" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_MaterialScienceEngineering";
CREATE TABLE "src_MaterialScienceEngineering" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_hasAssociateProfessor";
CREATE TABLE "src_hasAssociateProfessor" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_hasPostDoc";
CREATE TABLE "src_hasPostDoc" (c0 text , c1 text , c2 text , c3 text);
DROP TABLE IF EXISTS "src_isVisitingProfessorOf";
CREATE TABLE "src_isVisitingProfessorOf" (c0 text , c1 text , c2 text , c3 text);
DROP TABLE IF EXISTS "src_hasDegreeFrom";
CREATE TABLE "src_hasDegreeFrom" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Science";
CREATE TABLE "src_Science" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_English";
CREATE TABLE "src_English" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_hasAuthor";
CREATE TABLE "src_hasAuthor" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Dean";
CREATE TABLE "src_Dean" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_isTeachingAssistantOf";
CREATE TABLE "src_isTeachingAssistantOf" (c0 text , c1 text , c2 text , c3 text , c4 text);
DROP TABLE IF EXISTS "src_BiomedicalEngineering";
CREATE TABLE "src_BiomedicalEngineering" (c0 text);
DROP TABLE IF EXISTS "src_isCrazyAbout";
CREATE TABLE "src_isCrazyAbout" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_hasMajor";
CREATE TABLE "src_hasMajor" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_evaluatedBy";
CREATE TABLE "src_evaluatedBy" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_hasFullProfessor";
CREATE TABLE "src_hasFullProfessor" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Geosciences";
CREATE TABLE "src_Geosciences" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_hasMasterDegreeFrom";
CREATE TABLE "src_hasMasterDegreeFrom" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_CivilEngineering";
CREATE TABLE "src_CivilEngineering" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Reading";
CREATE TABLE "src_Reading" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_ElectiveCourse";
CREATE TABLE "src_ElectiveCourse" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_SportsFan";
CREATE TABLE "src_SportsFan" (c0 text);
DROP TABLE IF EXISTS "src_AeronauticalEngineering";
CREATE TABLE "src_AeronauticalEngineering" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_hasLecturer";
CREATE TABLE "src_hasLecturer" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Interest";
CREATE TABLE "src_Interest" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_ThesisEvaluationCommittee";
CREATE TABLE "src_ThesisEvaluationCommittee" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_isMemberOf";
CREATE TABLE "src_isMemberOf" (c0 text , c1 text , c2 text , c3 text);
DROP TABLE IF EXISTS "src_isStudentOf";
CREATE TABLE "src_isStudentOf" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_offerCourse";
CREATE TABLE "src_offerCourse" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Publication";
CREATE TABLE "src_Publication" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_LatinArts";
CREATE TABLE "src_LatinArts" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_CoEdCollege";
CREATE TABLE "src_CoEdCollege" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_SupplyChainManagement";
CREATE TABLE "src_SupplyChainManagement" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Software";
CREATE TABLE "src_Software" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_isOtherStaffOf";
CREATE TABLE "src_isOtherStaffOf" (c0 text , c1 text , c2 text , c3 text);
DROP TABLE IF EXISTS "src_Religions";
CREATE TABLE "src_Religions" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_hasAlumnus";
CREATE TABLE "src_hasAlumnus" (c0 text , c1 text , c2 text , c3 text);
DROP TABLE IF EXISTS "src_hasOtherStaff";
CREATE TABLE "src_hasOtherStaff" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_hasSubOrganization";
CREATE TABLE "src_hasSubOrganization" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Anthropology";
CREATE TABLE "src_Anthropology" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_hasDean";
CREATE TABLE "src_hasDean" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_isAssociateProfessorOf";
CREATE TABLE "src_isAssociateProfessorOf" (c0 text , c1 text , c2 text , c3 text);
DROP TABLE IF EXISTS "src_hasAge";
CREATE TABLE "src_hasAge" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Cricket";
CREATE TABLE "src_Cricket" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_ResearchAssistant";
CREATE TABLE "src_ResearchAssistant" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_ComputerEngineering";
CREATE TABLE "src_ComputerEngineering" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_ComputerScience";
CREATE TABLE "src_ComputerScience" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_ModernArts";
CREATE TABLE "src_ModernArts" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Manual";
CREATE TABLE "src_Manual" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Professor";
CREATE TABLE "src_Professor" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_BasketBallFan";
CREATE TABLE "src_BasketBallFan" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_hasThesisEvaluationCommittee";
CREATE TABLE "src_hasThesisEvaluationCommittee" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_hasResearchAssistant";
CREATE TABLE "src_hasResearchAssistant" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Director";
CREATE TABLE "src_Director" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Humanities";
CREATE TABLE "src_Humanities" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Course";
CREATE TABLE "src_Course" (c0 text);
DROP TABLE IF EXISTS "src_tenured";
CREATE TABLE "src_tenured" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_hasLastName";
CREATE TABLE "src_hasLastName" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_isDepartmentOf";
CREATE TABLE "src_isDepartmentOf" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_teachesCourse";
CREATE TABLE "src_teachesCourse" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_hasMember";
CREATE TABLE "src_hasMember" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Lecturer";
CREATE TABLE "src_Lecturer" (c0 text);
DROP TABLE IF EXISTS "src_loves";
CREATE TABLE "src_loves" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_hasEvaluationCommittee";
CREATE TABLE "src_hasEvaluationCommittee" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Astronomy";
CREATE TABLE "src_Astronomy" (c0 text , c1 text , c2 text , c3 text);
DROP TABLE IF EXISTS "src_Student";
CREATE TABLE "src_Student" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_ElectricalEngineering";
CREATE TABLE "src_ElectricalEngineering" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_worksFor";
CREATE TABLE "src_worksFor" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Article";
CREATE TABLE "src_Article" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_hasWork";
CREATE TABLE "src_hasWork" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_Person";
CREATE TABLE "src_Person" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Game";
CREATE TABLE "src_Game" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Music";
CREATE TABLE "src_Music" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_isResearchAssistantOf";
CREATE TABLE "src_isResearchAssistantOf" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_isLecturerOf";
CREATE TABLE "src_isLecturerOf" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_NonScienceStudent";
CREATE TABLE "src_NonScienceStudent" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_AssistantProfessor";
CREATE TABLE "src_AssistantProfessor" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_isCollegeOf";
CREATE TABLE "src_isCollegeOf" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_AssociateProfessor";
CREATE TABLE "src_AssociateProfessor" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_IndustryEngineering";
CREATE TABLE "src_IndustryEngineering" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_TeachingCourse";
CREATE TABLE "src_TeachingCourse" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_PerformingArts";
CREATE TABLE "src_PerformingArts" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_isAssistantProfessorOf";
CREATE TABLE "src_isAssistantProfessorOf" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_JournalArticle";
CREATE TABLE "src_JournalArticle" (c0 text , c1 text , c2 text , c3 text);
DROP TABLE IF EXISTS "src_isClericalStaffOf";
CREATE TABLE "src_isClericalStaffOf" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_hasCollege";
CREATE TABLE "src_hasCollege" (c0 text , c1 text , c2 text , c3 text);
DROP TABLE IF EXISTS "src_Painting";
CREATE TABLE "src_Painting" (c0 text);
DROP TABLE IF EXISTS "src_Tennis";
CREATE TABLE "src_Tennis" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_UGStudent";
CREATE TABLE "src_UGStudent" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_isPartOf";
CREATE TABLE "src_isPartOf" (c0 text , c1 text , c2 text , c3 text);
DROP TABLE IF EXISTS "src_Employee";
CREATE TABLE "src_Employee" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_Work";
CREATE TABLE "src_Work" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_hasPart";
CREATE TABLE "src_hasPart" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_hasProfessor";
CREATE TABLE "src_hasProfessor" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_isFullProfessorOf";
CREATE TABLE "src_isFullProfessorOf" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_PetroleumlEngineering";
CREATE TABLE "src_PetroleumlEngineering" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_isSupportingStaffOf";
CREATE TABLE "src_isSupportingStaffOf" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_WomanCollege";
CREATE TABLE "src_WomanCollege" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_hasHead";
CREATE TABLE "src_hasHead" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_hasResearchProject";
CREATE TABLE "src_hasResearchProject" (c0 text , c1 text , c2 text , c3 text);
DROP TABLE IF EXISTS "src_takesCourse";
CREATE TABLE "src_takesCourse" (c0 text , c1 text , c2 text , c3 text);
DROP TABLE IF EXISTS "src_hasCollegeDiscipline";
CREATE TABLE "src_hasCollegeDiscipline" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_hasStudent";
CREATE TABLE "src_hasStudent" (c0 text , c1 text , c2 text , c3 text);
DROP TABLE IF EXISTS "src_isSubOrganizationOf";
CREATE TABLE "src_isSubOrganizationOf" (c0 text , c1 text , c2 text , c3 text);
DROP TABLE IF EXISTS "src_isAdvisedBy";
CREATE TABLE "src_isAdvisedBy" (c0 text , c1 text , c2 text , c3 text);
DROP TABLE IF EXISTS "src_NonScience";
CREATE TABLE "src_NonScience" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_OtherStaff";
CREATE TABLE "src_OtherStaff" (c0 text);
DROP TABLE IF EXISTS "src_MarineScience";
CREATE TABLE "src_MarineScience" (c0 text);
DROP TABLE IF EXISTS "src_BasketBall";
CREATE TABLE "src_BasketBall" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_PublicRelationsManagement";
CREATE TABLE "src_PublicRelationsManagement" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_hasEmployee";
CREATE TABLE "src_hasEmployee" (c0 text , c1 text , c2 text , c3 text);
DROP TABLE IF EXISTS "src_AsianArts";
CREATE TABLE "src_AsianArts" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_likes";
CREATE TABLE "src_likes" (c0 text , c1 text , c2 text);
DROP TABLE IF EXISTS "src_isFacultyOf";
CREATE TABLE "src_isFacultyOf" (c0 text , c1 text , c2 text , c3 text , c4 text);
DROP TABLE IF EXISTS "src_OperationsManagement";
CREATE TABLE "src_OperationsManagement" (c0 text);
DROP TABLE IF EXISTS "src_hasTitle";
CREATE TABLE "src_hasTitle" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_EmployeeEvaluationCommittee";
CREATE TABLE "src_EmployeeEvaluationCommittee" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_ConferencePaper";
CREATE TABLE "src_ConferencePaper" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_History";
CREATE TABLE "src_History" (c0 text);
DROP TABLE IF EXISTS "src_StudentEvaluationCommittee";
CREATE TABLE "src_StudentEvaluationCommittee" (c0 text);
DROP TABLE IF EXISTS "src_PhDStudent";
CREATE TABLE "src_PhDStudent" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_RiskManagement";
CREATE TABLE "src_RiskManagement" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_CollegeDiscipline";
CREATE TABLE "src_CollegeDiscipline" (c0 text , c1 text);
DROP TABLE IF EXISTS "src_hasProgram";
CREATE TABLE "src_hasProgram" (c0 text , c1 text , c2 text , c3 text);
DROP TABLE IF EXISTS "src_UGCourse";
CREATE TABLE "src_UGCourse" (c0 text , c1 text , c2 text);
