DROP TABLE IF EXISTS "src_AcquisitionTEMP";
CREATE TABLE "src_AcquisitionTEMP" (c0 text);
DROP TABLE IF EXISTS "src_TransactionTEMP";
CREATE TABLE "src_TransactionTEMP" (c0 text);
DROP TABLE IF EXISTS "src_AddressTEMP";
CREATE TABLE "src_AddressTEMP" (c0 text);
DROP TABLE IF EXISTS "src_ThingTEMP";
CREATE TABLE "src_ThingTEMP" (c0 text);
DROP TABLE IF EXISTS "src_inverseofhasAddressTEMP";
CREATE TABLE "src_inverseofhasAddressTEMP" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_CompanyTEMP";
CREATE TABLE "src_CompanyTEMP" (c0 text);
DROP TABLE IF EXISTS "src_LegalPersonTEMP";
CREATE TABLE "src_LegalPersonTEMP" (c0 text);
DROP TABLE IF EXISTS "src_DealerTEMP";
CREATE TABLE "src_DealerTEMP" (c0 text);
DROP TABLE IF EXISTS "src_StockBrokerTEMP";
CREATE TABLE "src_StockBrokerTEMP" (c0 text);
DROP TABLE IF EXISTS "src_InvestorTEMP";
CREATE TABLE "src_InvestorTEMP" (c0 text);
DROP TABLE IF EXISTS "src_PersonTEMP";
CREATE TABLE "src_PersonTEMP" (c0 text);
DROP TABLE IF EXISTS "src_OfferTEMP";
CREATE TABLE "src_OfferTEMP" (c0 text);
DROP TABLE IF EXISTS "src_hasAddressTEMP";
CREATE TABLE "src_hasAddressTEMP" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_PhysicalPersonTEMP";
CREATE TABLE "src_PhysicalPersonTEMP" (c0 text);
DROP TABLE IF EXISTS "src_StockTEMP";
CREATE TABLE "src_StockTEMP" (c0 text);
DROP TABLE IF EXISTS "src_FinantialInstrumentTEMP";
CREATE TABLE "src_FinantialInstrumentTEMP" (c0 text);
DROP TABLE IF EXISTS "src_isListedInTEMP";
CREATE TABLE "src_isListedInTEMP" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_belongsToCompanyTEMP";
CREATE TABLE "src_belongsToCompanyTEMP" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_StockExchangeMemberTEMP";
CREATE TABLE "src_StockExchangeMemberTEMP" (c0 text);
DROP TABLE IF EXISTS "src_tradesOnBehalfOfTEMP";
CREATE TABLE "src_tradesOnBehalfOfTEMP" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_StockTraderTEMP";
CREATE TABLE "src_StockTraderTEMP" (c0 text);
DROP TABLE IF EXISTS "src_TraderTEMP";
CREATE TABLE "src_TraderTEMP" (c0 text);
DROP TABLE IF EXISTS "src_isExecutedForTEMP";
CREATE TABLE "src_isExecutedForTEMP" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_isExecutedByTEMP";
CREATE TABLE "src_isExecutedByTEMP" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_involvesInstrumentTEMP";
CREATE TABLE "src_involvesInstrumentTEMP" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_hasStockTEMP";
CREATE TABLE "src_hasStockTEMP" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_StockExchangeListTEMP";
CREATE TABLE "src_StockExchangeListTEMP" (c0 text);
DROP TABLE IF EXISTS "src_listsStockTEMP";
CREATE TABLE "src_listsStockTEMP" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_isTradedInTEMP";
CREATE TABLE "src_isTradedInTEMP" (c0 text, c1 text);
DROP TABLE IF EXISTS "src_usesBrokerTEMP";
CREATE TABLE "src_usesBrokerTEMP" (c0 text, c1 text);